Cleaning up dnssec docs
miekg/coredns pull request #1016
Opened 2017-09-01 14:46 UTC by bradbeam

- Removing mention of autogeneration of dnssec keys since this feature isn't implemented
- Proposing to standardize on not specifying signing key suffix ( [code](https://github.com/coredns/coredns/blob/master/middleware/dnssec/setup.go#L113) can handle suffixes, but when providing examples it's unclear on what format should be used )
- Updating syntax to be all inclusive of options ( perhaps it's worth adding in a note on which fields are optional ). This is probably something we'd want to investigate changing for all middleware. 
- Added an additional example for kubernetes

2017-09-01 16:47 UTC, miekg commented on middleware/dnssec/README.md
> +  `.private` or `.key` suffix.
Note that using `.key` of `.private` is actually supported. Base name will be "calculated" from that.

2017-09-01 16:48 UTC, miekg requested changes
.key/.private is supported. Apart from that lgtm.

2017-09-01 16:57 UTC, bradbeam commented
Yeah I saw it was supported. That gives 3 variations for how the key file can be specified which can lead to confusion. I'll update to show the various supported formats.

2017-09-02 16:41 UTC, miekg approved these changes

2017-09-02 16:41 UTC, merged