WIP:  Enable dnstap plugin to insert other plugin's specific data into extra field of tap.Dnstap message
miekg/coredns pull request #1101
Opened 2017-09-21 21:45 UTC by huynhmb359

### 1. What does this pull request do
This PR enables dnstap plugin to insert other plugin's specific data into extra field of tap.Dnstap message.    

- Dnstap allocates a map where other plugins can add their extra data.   Key is the plugin name and value is the DnstapExtra.    DnstapExtra is a map where extra data per message type are stored.  Key is the message type (i.e.  CQ,  CR  ...etc) .  Value is the wire data in byte array.  

- We define a new structure where the extra data for various plugins can be written into the tap.Dnstap's extra using protobuf.   The structure called Extra.  It's map  with key is the name of the plugin and value is the extra data. 

- When sending out the dnstap message,  dnstap plugin will use the data in the map in the context to construct Extra data and then sends in the tap.DnsTap. 

 2. Which issues (if any) are related?
There is no issue opened for this.

### 3. Which documentation changes (if any) need to be made?
No document change

I'll add UTs after the approach accepted.

2017-09-23 06:30 UTC, miekg commented
/cc @varyoo 

I think this can work. Making a new map on every connection is somewhat expensive though - what amount of data can actually be put here? I only see a `[]byte`.

2017-09-24 22:39 UTC, huynhmb359 commented
For now it's only []byte.  Middleware can put its own serialize data here.

2017-09-25 00:25 UTC, varyoo commented
If a middleware wants to send a custom dnstap client response maybe it should do it completely and signal the dnstap middleware not to do it before the response is written.

2017-09-25 16:00 UTC, johnbelamaric commented
@varyoo in that case I guess we can get rid of the map creation. on the other hand, only one middleware can add that data, rather than accumulating stuff from all the middleware.

As of today, that works for our use case - we only need to do it with one middleware.

@huynhmb359 can we create the map only if we need it - that is, in the policy MW? Though, then we take a perf hit which we won't in @varyoo's solution. Hmm..

I guess given that we don't *need* multiple middleware to do it today, and there is a performance cost to doing that, we are better off taking @varyoo's suggestion. I think that means sticking a boolean in the context, and having the dnstap plugin skip the CR in that case. Make sense?

2017-09-25 16:08 UTC, huynhmb359 commented
OK, I will fix according to both @varyoo  and @johnbelamaric  suggestion.

2017-09-25 16:22 UTC, miekg commented
you can also just append to a `[][]byte` in the context?

2017-09-25 21:49 UTC, huynhmb359 commented
Not sure why my recent commit :  https://github.com/huynhmb359/coredns/commit/8b33d0a26b591d7e7637113fac705af7beae361c  
does not go into this PR?    

Any suggestion?   Should I close this PR and recreate?

2017-09-26 15:20 UTC, johnbelamaric requested changes
Nit: Just fix the comment then this LGTM.

2017-09-26 15:20 UTC, johnbelamaric commented on plugin/dnstap/taprw/writer.go
> +// saves the extra data.  Value is a DnstapExtra.
Fix the comment.

2017-09-26 15:26 UTC, huynhmb359 commented on plugin/dnstap/taprw/writer.go
> +// saves the extra data.  Value is a DnstapExtra.
It's fixed.  Thnx.

2017-09-26 15:42 UTC, johnbelamaric commented
I think the test failed due to this merging in upstream miekg/dns: https://github.com/miekg/dns/pull/513

2017-09-29 20:38 UTC, merged