add goroutine to check hosts file for updates
miekg/coredns pull request #1180
Opened 2017-10-28 06:55 UTC by pmoroney

### 1. What does this pull request do?
Creates a goroutine in `OnStartup()` to check the hosts file for changes.
Refactors how the corefile inline hosts file gets fed to the parser.

Basically I took the three maps that are used for lookups and created a struct, `hostsMap`, to hold them.
Then I made `parse()` return that struct and accept an override as a parameter.
So `parse()` is used to create a `hostsMap` from a reader.
Initially, if an inline hostsfile exists it is parsed and the resulting `hostsMap` is set to `Hostsfile.inline`
A goroutine is created that runs `ReadFile()` every 5 seconds. (I kept that duration from the previous implementation, but I'm not married to it)
`ReadFile()` checks the file status to see if it has changed, if it has, it calls `parse()` on the file with `h.inline` as the override and sets the resulting `hostsMap` to `Hostsfile.hmap` which is what is used by the lookup functions.

### 2. Which issues (if any) are related?
N/A

### 3. Which documentation changes (if any) need to be made?
N.A

2017-10-28 08:24 UTC, miekg requested changes
Looks good! Some nits and comments.

2017-10-28 08:24 UTC, miekg commented on plugin/hosts/hostsfile.go
> +	if err != nil {
This might benefit from a short comment that we don't care if the file does not exist (hence we're not returning `err`)

2017-10-28 08:24 UTC, miekg commented on plugin/hosts/hostsfile.go
> +func (h *Hostsfile) parseFile(file io.Reader) {
`parseFile` -> `parseReader`? And just use `r` for the io.Reader instead of `file`?

2017-10-28 08:24 UTC, miekg commented on plugin/hosts/hostsfile.go
> +func (h *Hostsfile) parse(file io.Reader, override *hostsMap) *hostsMap {
`file` -> `r` as a var

2017-10-28 08:24 UTC, miekg commented on plugin/hosts/hostsfile.go
> +	if override != nil {
I would just return here if `override == nil` and then do the override thing below

2017-10-28 08:24 UTC, miekg commented on plugin/hosts/setup.go
> +		if err != nil {
which `err` is referenced here?

2017-10-28 08:24 UTC, miekg commented on plugin/hosts/setup.go
> +			ticker := time.NewTicker(5 * time.Second)
This deserves a small sentence in the README.md (e.g. "We scan for changes every 5s." or something)

2017-10-30 23:33 UTC, pmoroney commented
I have made the requested changes. Thank's for catching those.

2017-10-31 07:40 UTC, miekg approved these changes

2017-10-31 07:40 UTC, merged