Add docker image to be a manifest list
miekg/coredns pull request #1195
Opened 2017-11-02 18:51 UTC by rajansandeep

### 1. What does this pull request do?
Includes Docker image to be a manifest list.

### 2. Which issues (if any) are related?
#1177 

### 3. Which documentation changes (if any) need to be made?

2017-11-02 18:54 UTC, miekg requested changes

2017-11-02 18:54 UTC, miekg commented on Makefile.release
> +ifeq (, $(shell ls | grep manifest-tool ))
Don't assume this is locally installed. Might be in $PATH.

2017-11-02 20:12 UTC, miekg approved these changes

2017-11-02 20:15 UTC, merged

2017-11-02 20:49 UTC, yongtang commented
@rajansandeep The base image has to be from different architecture and the binary should used the generated binary form different directories. It should not use the same binary.

2017-11-02 20:52 UTC, yongtang commented
The binary seems to be fine as `tar -xzf ` is used. Need to change the base image.

2017-11-03 07:23 UTC, miekg commented
@yongtang what remains to be done here?
(If we want to do a quick 0.9.10, this the last outstanding issue)

2017-11-03 14:41 UTC, rajansandeep commented
Per the docs: https://hub.docker.com/r/library/alpine/ 

Supported Architectures:
amd64, arm32v6, arm64v8, i386, ppc64le, s390x
As of 2017-09-12, these other architectures are included under the non-prefixed images via "manifest lists" .

So we should be fine as is.

2017-11-03 16:12 UTC, yongtang commented
@rajansandeep @miekg Let's hold on for that. The base image is multi arch. However, at the time the coredns docker image is built, the `docker build` is running on a amd64 machine (the dev machine) and the binary will only be added to amd64 docker image.

There are some additional steps to be done. See steps in:
https://github.com/luxas/kubeadm-workshop/blob/master/images/nodejs/Makefile

I am preparing the PR and will open the PR shortly.

2017-11-03 16:15 UTC, miekg commented
ok