plugin/rewrite: add response rewrite docs
miekg/coredns pull request #1414
Opened 2018-01-22 20:12 UTC by greenpau

### 1. What does this pull request do?

Add DNS response re-write documentation for `plugin/rewrite`.

### 2. Which issues (if any) are related?

See: https://github.com/coredns/coredns/issues/1313#issuecomment-358983475

### 3. Which documentation changes (if any) need to be made?

The `plugin/rewrite` documentation.

2018-01-22 20:12 UTC, greenpau commented
@johnbelamaric , per your request, please review.

2018-01-22 20:23 UTC, johnbelamaric requested changes
Looks pretty good. Some nits. Also:

1. Add a general syntax for the long form/answer rules. I think the way the parser works you can put multiple rules inside the braces.

2. Move the Name Rewrites section above the EDNS0 section, since I think it will be more common.

2018-01-22 20:23 UTC, johnbelamaric commented on plugin/rewrite/README.md
> +When re-writing incoming DNS requests' names, `coredns` re-write the `QUESTION SECTION`
s/`coredns`/CoreDNS/

s/re-write/re-writes/

2018-01-22 20:23 UTC, johnbelamaric commented on plugin/rewrite/README.md
> +`coredns` configuration file has the following rule:
s/`coredns`/CoreDNS/

2018-01-22 20:23 UTC, johnbelamaric commented on plugin/rewrite/README.md
> +`coredns` instance re-wrote the request to `ftp-us-west-1.coredns.rocks` with
ditto

2018-01-22 22:25 UTC, greenpau commented
> Add a general syntax for the long form/answer rules.

@johnbelamaric , will do.

> I think the way the parser works you can put multiple rules inside the braces.

@johnbelamaric , I don't think so. One rule per curly brace.

2018-01-22 22:25 UTC, greenpau commented
> Move the Name Rewrites section above the EDNS0 section, since I think it will be more common.

@johnbelamaric , ack!

2018-01-22 22:35 UTC, greenpau commented
@johnbelamaric , please review once again.

2018-01-23 03:01 UTC, johnbelamaric approved these changes

2018-01-23 03:01 UTC, merged