WIP: Fix TLS configuration for forward.
miekg/coredns pull request #1679
Opened 2018-04-13 16:56 UTC by miekg

2018-04-14 13:52 UTC, miekg commented
Not sure if related, but:
~~~
default/coredns-deployment-664ddc7d9-htl22[coredns]: 14/Apr/2018:13:51:48 +0000 [PANIC registry-1.docker.io. AAAA] /home/miek/upstream/go/src/sync/atomic/asm_linux_arm.s:109 - runtime error: invalid memory address or nil pointer dereference
~~~

2018-04-17 18:52 UTC, miekg commented
anyone else available for review as well? /cc @rdrozhdzh @grobie ?

2018-04-18 15:06 UTC, rdrozhdzh requested changes
What was the reason of moving tlsConfig from transport to Proxy? Now we have to pass it in each `dial()`. IMO the transport related changes were not necessary.

2018-04-18 15:06 UTC, rdrozhdzh commented on plugin/forward/connect.go
> +	if forceTCP && proto == "udp" {
this overwrites "tcp-tls" if it was set 3 lines above. Consider `else if`

2018-04-18 15:06 UTC, rdrozhdzh commented on plugin/forward/setup.go
> +			pr.setTLSConfig(f.tlsConfig)
this will turn non-tls upstreams to tls, since you removed `if protocols[i] == TLS`

2018-04-18 16:38 UTC, rdrozhdzh commented
I think the basic fix for #1672 could be like adding
```
if f.tlsConfig == nil {
	f.tlsConfig = new(tls.Config)
}

```
before 
https://github.com/coredns/coredns/blob/9a7e487a5aac4643baf6b385cc2d8c444e648221/plugin/forward/setup.go#L138-L140

plus the change you made in Proxy.setTLSConfig() to update tlsClient

2018-04-18 18:56 UTC, miekg commented
Thanks for the review @rdrozhdzh . You raise a good point with moving the tls from transport, that should have been necessary. Let me see if I can put that back easily.

2018-04-21 17:16 UTC, miekg commented
Closing in favor of https://github.com/coredns/coredns/pull/1714

Thanks @rdrozhdzh, really helpful review - closing this PR.

2018-04-21 17:16 UTC, closed without merging