Update all plugins to use plugin/pkg/log
miekg/coredns pull request #1694
Opened 2018-04-18 20:37 UTC by miekg

I wish this could have been done with sed. Alas manually changed all
callers to use the new plugin/pkg/log package.

2018-04-18 20:38 UTC, miekg commented
also dropping a bunch of log.SetOutput(ioutil.Discard) in tests.

2018-04-18 21:44 UTC, johnbelamaric requested changes
One minor tweak needed.

2018-04-18 21:44 UTC, johnbelamaric commented on plugin/dnstap/dnstapio/io.go
> +			log.Error("Reconnected to dnstap")
Should be Info.

2018-04-19 06:18 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Update all pl..." ]
>johnbelamaric requested changes on this pull request.
>
>One minor tweak needed.
>
>>  		} else {
>-			log.Print("[INFO] Reconnected to dnstap")
>+			log.Error("Reconnected to dnstap")
>
>Should be Info.

done

2018-04-19 06:41 UTC, merged