Enforcing gofmt -s on linter check
miekg/coredns pull request #1820
Opened 2018-05-19 23:05 UTC by yongtang

### 1. What does this pull request do?
This fix enforces gofmt -s on linter check in Makefile,
and fixes plugin/kubernetes/handler_test.go with `gofmt -s`

### 2. Which issues (if any) are related?

### 3. Which documentation changes (if any) need to be made?

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-05-20 01:28 UTC, greenpau commented
@yongtang , the integration test is failing. Please address and ping me back.

2018-05-20 02:12 UTC, greenpau requested changes
Please fix the integration test. Several files are not formatted in accordance with the new standard.

2018-05-20 14:52 UTC, yongtang commented
Interesting, golang 1.9 and 1.10 have differences with gofmt:
```
diff --git a/plugin/tls/tls_test.go b/plugin/tls/tls_test.go
index 84a74ae3..0bbba18a 100644
--- a/plugin/tls/tls_test.go
+++ b/plugin/tls/tls_test.go
@@ -14,8 +14,8 @@ func TestTLS(t *testing.T) {
                expectedRoot       string // expected root, set to the controller. Empty for negative cases.
                expectedErrContent string // substring from the expected error. Empty for positive cases.
        }{
-       // positive
-       // negative
+               // positive
+               // negative
        }
 
        for i, test := range tests {
```

I think coredns/ci may need to update to 1.10.

2018-05-20 14:55 UTC, yongtang commented
/cc @chrisohaver Any way to change the coredns/ci so that it has the same version of golang (1.9 or 1.10) with continuous-integration/travis-ci/pr ?

2018-05-21 07:07 UTC, miekg commented
Hmm. I've *manually* upgraded the go version to  go1.10.2 linux/amd64

2018-05-21 12:40 UTC, chrisohaver commented
> Hmm. I've manually upgraded the go version to go1.10.2 linux/amd64

Thanks, yes, manual is the way to upgrade go for coredns/ci.

2018-05-21 12:42 UTC, chrisohaver commented
How is the new format different than before?

Didn't we already enforce gofmt in make?  Why the change?

2018-05-21 12:50 UTC, chrisohaver commented
> Didn't we already enforce gofmt in make? Why the change?

I see.  It was moved to the linter in September, then removed from linter in February on the assumption it was being performed twice...  but it seems it was the only check at the time.

2018-05-21 13:26 UTC, chrisohaver commented
/integration

2018-05-21 13:38 UTC, chrisohaver commented
@greenpau, all checks pass now.

2018-05-21 13:50 UTC, greenpau approved these changes

2018-05-21 13:52 UTC, merged