plugin/template: fix CNAME upstream handling
miekg/coredns pull request #1886
Opened 2018-06-19 14:18 UTC by chrisohaver

### 1. Why is this pull request needed and what does it do?

Fixes a couple of bugs with template CNAME lookup handling...
1. if `upstream` is not set, we'd return a SERVFAIL if a CNAME was in the response.
2. CNAME target lookup was being performed on CNAME queries (not just A and AAAA queries).  Expected behavior is that a query for CNAME records only returns the CNAME records.  Lookup and adding of A/AAAA records should only be done for A/AAAA queries.

### 2. Which issues (if any) are related?

none.

### 3. Which documentation changes (if any) need to be made?

none

2018-06-19 14:23 UTC, chrisohaver commented
oops - i need to remove that extraneous unrelated file...

2018-06-19 15:03 UTC, greenpau commented
@chrisohaver , any unit test improvements?

2018-06-19 15:08 UTC, greenpau requested changes

2018-06-19 15:08 UTC, greenpau commented on plugin/template/template.go
> +			if template.upstream != nil && (state.QType() == dns.TypeA || state.QType() == dns.TypeAAAA) && rr.Header().Rrtype == dns.TypeCNAME {
@chrisohaver , please add unit tests.

2018-06-19 19:24 UTC, greenpau commented
@chrisohaver , please let me know when you are done with this PR. I will approve.

2018-06-21 14:58 UTC, chrisohaver commented
I could not work out how to test upstream function with "unit" tests, so added an integration test.

2018-06-21 15:29 UTC, greenpau commented
> I could not work out how to test upstream function with "unit" tests, so added an integration test.

@miekg , I am also not sure about this one. The integration test is great, but unit test is better, imho. What is your take on this?

2018-06-21 16:46 UTC, chrisohaver commented
To be clear, the integration test is in `/test`, where other similar integration tests reside.  Most of these tests run a server instance with a given corefile - hence they are technically integration tests, not strictly unit tests.

There is a similar test that tests CNAME upstream lookups for the `file` plugin (`/test/file_upstream_test.go`).

There _may_ be a way to test upstream lookups without running a server instance... but I don't see a pressing reason to do so.

2018-06-21 16:53 UTC, chrisohaver commented
> There may be a _way_ to test upstream lookups without running a server instance.

Actually - I could do it by creating an interface for `upstream`, `upstreamer`, and mocking it out with a something that implements `upstreamer`...  this would require some refactoring in `template`.

2018-06-21 17:03 UTC, miekg approved these changes
there is test, the only downside is that codecov doesn't count it correctly

2018-06-21 18:34 UTC, greenpau commented
> there is test, the only downside is that codecov doesn't count it correctly

@miekg , 👍 , will remember this for the future. Thought it is better to ask.

2018-06-21 18:35 UTC, greenpau commented
@chrisohaver , do you mind squashing? (or perhaps it is done automatically)

2018-06-21 18:38 UTC, merged

2018-06-22 06:46 UTC, miekg commented
@greenpau we squash on commit (which should a project wide setting). Don't care that much on how the exact commit message looks.