plugin/kubernetes: add watch option
miekg/coredns pull request #2157
Opened 2018-10-02 18:59 UTC by miekg

Disable watch by default (takes up mem) and allows user to override by
setting watch.

Update the README.md to match.

Fixes: #2156

Signed-off-by: Miek Gieben <miek@miek.nl>

### 1. Why is this pull request needed and what does it do?

### 2. Which issues (if any) are related?

### 3. Which documentation changes (if any) need to be made?

2018-10-03 00:44 UTC, johnbelamaric requested changes
I get the idea, but I am not sure it's viable. The endpoint comparison is necessary, because endpoints get lots of updates that are completely irrelevant and don't change the DNS records at all.

2018-10-03 00:44 UTC, johnbelamaric commented on plugin/kubernetes/README.md
> +* `watch` enables updates being send to a server listening for watching on a gRPC channel.
How about:

`watch` enables sending updates to clients subscribed to records using the gRPC Watch streaming API call

2018-10-03 00:44 UTC, johnbelamaric commented on plugin/kubernetes/controller.go
> +	upd := func(old, new interface{}) { dns.updateModifed() }
I don't think this is a good idea. Without the endpoint subsets comparison operations, there will be a continuous stream of updates requiring new AXFRs even though there is no actual, relevant change.

2018-10-03 06:18 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>johnbelamaric requested changes on this pull request.
>
>I get the idea, but I am not sure it's viable. The endpoint comparison is necessary, because endpoints get lots of updates that are completely irrelevant and don't change the DNS records at all.
>
>> @@ -106,6 +107,7 @@ kubernetes [ZONES...] {
> * `ignore empty_service` return NXDOMAIN for services without any ready endpoint addresses (e.g. ready pods).
>   This allows the querying pod to continue searching for the service in the search path.
>   The search path could, for example, include another kubernetes cluster.
>+* `watch` enables updates being send to a server listening for watching on a gRPC channel.
>
>How about:
>
>`watch` enables sending updates to clients subscribed to records using the gRPC Watch streaming API call


ack.

>> @@ -109,6 +109,14 @@ func newdnsController(kubeClient kubernetes.Interface, opts dnsControlOpts) *dns
> 		zones:            opts.zones,
> 		endpointNameMode: opts.endpointNameMode,
> 	}
>+	add := func(obj interface{}) { dns.updateModifed() }
>+	del := func(obj interface{}) { dns.updateModifed() }
>+	upd := func(old, new interface{}) { dns.updateModifed() }
>
>I don't think this is a good idea. Without the endpoint subsets comparison operations, there will be a continuous stream of updates requiring new AXFRs even though there is no actual, relevant change.

Ok, I couldn't easily find anymore what we had here originally.

2018-10-03 13:23 UTC, chrisohaver commented
> Disable watch by default (takes up mem) ...

Do we know how much memory it takes up?

2018-10-03 16:24 UTC, johnbelamaric commented
We had what you are proposing originally, but while doing the watch, I
found that I was getting continuous updates, and the serial was changing
all the time. So that's why we implemented the other bits. It's still
relevant with or without the watch.

On Tue, Oct 2, 2018 at 11:18 PM Miek Gieben <notifications@github.com>
wrote:

> [ Quoting <notifications@github.com> in "Re: [coredns/coredns]
> plugin/kubern..." ]
> >johnbelamaric requested changes on this pull request.
> >
> >I get the idea, but I am not sure it's viable. The endpoint comparison is
> necessary, because endpoints get lots of updates that are completely
> irrelevant and don't change the DNS records at all.
> >
> >> @@ -106,6 +107,7 @@ kubernetes [ZONES...] {
> > * `ignore empty_service` return NXDOMAIN for services without any ready
> endpoint addresses (e.g. ready pods).
> > This allows the querying pod to continue searching for the service in
> the search path.
> > The search path could, for example, include another kubernetes cluster.
> >+* `watch` enables updates being send to a server listening for watching
> on a gRPC channel.
> >
> >How about:
> >
> >`watch` enables sending updates to clients subscribed to records using
> the gRPC Watch streaming API call
>
>
> ack.
>
> >> @@ -109,6 +109,14 @@ func newdnsController(kubeClient
> kubernetes.Interface, opts dnsControlOpts) *dns
> > zones: opts.zones,
> > endpointNameMode: opts.endpointNameMode,
> > }
> >+ add := func(obj interface{}) { dns.updateModifed() }
> >+ del := func(obj interface{}) { dns.updateModifed() }
> >+ upd := func(old, new interface{}) { dns.updateModifed() }
> >
> >I don't think this is a good idea. Without the endpoint subsets
> comparison operations, there will be a continuous stream of updates
> requiring new AXFRs even though there is no actual, relevant change.
>
> Ok, I couldn't easily find anymore what we had here originally.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/2157#issuecomment-426523806>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AJB4s9Z32vq04g_7I2yTX8AB2GL3kZw6ks5uhFajgaJpZM4XEqkH>
> .
>

2018-10-09 20:55 UTC, miekg commented
dropping

2018-10-09 20:55 UTC, closed without merging