Forward: introduce `Opt` builder for creating plugin instance.
miekg/coredns pull request #2184
Opened 2018-10-11 13:27 UTC by bcho

fixes: #2182

### 1. Why is this pull request needed and what does it do?

This pull request adds a simple implementation for #2182, which decouples the forward plugin building logic, and enables reusing later.

### 2. Which issues (if any) are related?

#2182 

### 3. Which documentation changes (if any) need to be made?

forward plugin's `New` method may be marked as deprecated

2018-10-12 18:09 UTC, johnbelamaric requested changes
A few minor tweaks but otherwise lgtm. I know thought that @miekg has had concerns in the past about exposing this sort of thing in a plugin, rather than moving to a common pkg.

2018-10-12 18:09 UTC, johnbelamaric commented on plugin/forward/forward.go
> +func (o Opt) Build() *Forward {
This should be (o *Opt) or it will make a copy.

2018-10-12 18:09 UTC, johnbelamaric commented on plugin/forward/setup.go
> +func parseBlock(c *caddyfile.Dispenser, opt *Opt) error {
Why name it "opt" here and "o" everywhere else?

2018-10-13 00:57 UTC, bcho commented
@johnbelamaric changes updated, PTAL.

> concerns in the past about exposing this sort of thing in a plugin, rather than moving to a common pkg

Yep, I have the same concern too, but I don't find any implementations applying this way. @miekg any suggestions here?

2018-10-13 17:59 UTC, johnbelamaric commented
/lgtm

2018-10-29 21:03 UTC, miekg commented
How is this different than just exposing the bits you need?

The problem with the approach is this now puts a requirement on this pluign to not break this api - there was never a thing like this before, so it's a pretty big change.

What's the usecase here and why can this not be solved by the various Lookup functions that are sort of the entry point for other plugin into this one?
(even with something like this in place it will break at some point, because there isn't any inherit guarantee being agreed here)

2018-10-31 04:45 UTC, bcho commented
Hi @miekg 

> What's the usecase here

The main use case is to allow other plugins to embed forward plugin's capacity (basically, to use `Forward.ServeDNS`).

For now, `Forward` holds some internal fields and I think it can be instantiated by an `Opt` builder. This builder actually reduces some dependencies between the caller and the callee IMO. Of course, this kind of usage requires the API to be stable, as the use case is just want to create dependencies between plugins.

But I come up with a better way, like just copy the `ServeDNS` logic into my plugin like that:

```go
import (
  "github.com/coredns/coredns/plugin/forward"
)

func (p MyPlugin) ServeDNS(ctx context.Context, w dns.ResponseWriter, r *dns.Msg) {
  if fallbackToForward(ctx, w, r) {
    p.serveDNSWithForward(ctx, w, r)
  }
}

func (p MyPlugin) serveDNSWithForward(// ...) {
  var proxies []*forward.Proxy
  // using proxy as the same way forward does
}
```

So I think it's ok to close this pull request by now.

2018-10-31 04:45 UTC, closed without merging