plugin/cache: allow disabling of positive/negative cache
miekg/coredns pull request #2883
Opened 2019-06-11 22:27 UTC by chrisohaver

### 1. Why is this pull request needed and what does it do?

Allows users to specify zero for positive or negative cache to disable the corresponding cache.

This expands on #2588, ...
* skips initialization of a cache if disabled (zero length)
* adds unit test
* updates README

### 2. Which issues (if any) are related?

#2588 (stalled)

### 3. Which documentation changes (if any) need to be made?

included

### 4. Does this introduce a backward incompatible change or deprecation?

not realistically

2019-06-12 06:58 UTC, miekg commented
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/cache: all..." ]
>### 1. Why is this pull request needed and what does it do?
>
>Allows users to specify zero for positive or negative cache to disable the corresponding cache.

If you don't want to cache you can disable the cache plugin.


/Miek

--
Miek Gieben

2019-06-12 12:52 UTC, chrisohaver commented
> If you don't want to cache you can disable the cache plugin. /Miek

Disabling the cache plugin disables both positive and negative cache.  The use case here is to disable only one.  For example, disabling the negative cache.

2019-06-17 19:59 UTC, stp-ip commented
Looks good from my point of view. Reasonable addition in functionality. Still would like an additional sign off by Miek or another reviewer.

2019-06-19 10:24 UTC, miekg commented
updating the readme and adding test is all good. The original PR was only a couple of lines though; this adds more. I'm not fond of the cache type as we already had a `switch` in the `set` method anyway - i.e. the cache type adds an indirection that not directly needed.

2019-06-19 14:02 UTC, chrisohaver commented
The original PR initializes an empty cache of minimum size, which is a waste of memory.
This PR skips initializing the corresponding cache if it's not going to be used.
The original PR also wastes time searching disabled caches for each get.
This PR skips searching a cache if it is disabled.

2019-07-01 07:14 UTC, miekg requested changes
We're also doing this because Python is stupid: https://stackoverflow.com/questions/54778160/python-requests-library-not-resolving-non-authoritative-dns-lookups

That's fixed with 1.5.1 so I don't see why this is needed, is it creates (slightly) more complexity on our side.

So NACK

2019-07-01 07:14 UTC, miekg commented on plugin/cache/cache.go
> +		return noCache
Please remove this indirection; it's not needed and it bolts an indirection on an indirection

2019-07-01 07:14 UTC, miekg commented on plugin/cache/cache.go
> +	negCache = 2 // should go in negative cache
please remove

2019-07-01 07:14 UTC, miekg commented on plugin/cache/README.md
> + . {
We should get out of the habit of doing every example with `.`, please change this into into `example.org`, most examples also include a valid Corefile so add a forward in here or just *whoami*

2019-07-01 17:43 UTC, chrisohaver commented
This is done for a general use case.  Not just for the python issue.
One general use case is that some people disable negative cache in micro-service type environments.
But I don't care about this strongly.  So closing...

2019-07-01 17:43 UTC, closed without merging