document route53 IAM policy
miekg/coredns pull request #3050
Opened 2019-07-27 07:58 UTC by bobzoller

### 1. Why is this pull request needed and what does it do?
This PR documents the required IAM permissions to use the route53 plugin.  AFAICT, the alternative is to read the source code and AWS docs to figure it out.

### 2. Which issues (if any) are related?
- #2924 
- #2859
- #2983 

### 3. Which documentation changes (if any) need to be made?
This is _only_ a documentation change!

### 4. Does this introduce a backward incompatible change or deprecation?
No.

2019-07-27 08:28 UTC, miekg commented
fyi: the docs in man/ are generated, so you don't have to include them here. The READM.md is the canonical doc.

2019-07-27 08:34 UTC, miekg commented
Is it possible to add a `## Also See` section at the end to link to extra documentation that has a stable URL?

2019-07-31 19:27 UTC, dilyevsky requested changes

2019-07-31 19:27 UTC, dilyevsky commented on man/coredns-route53.7
> +    aws\_access\_key [AWS\_ACCESS\_KEY\_ID AWS\_SECRET\_ACCESS\_KEY]
Both `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are required.

2019-08-29 06:33 UTC, miekg commented
are you able to change the PR according to the comments? Otherwise I'll close it.

2019-09-02 16:03 UTC, miekg commented
closing this tomorrow - if I can remember to do it.

2019-09-03 13:15 UTC, closed without merging