Add release note for v1.6.6
miekg/coredns pull request #3531
Opened 2019-12-11 15:25 UTC by yongtang

Part of #3519 for v1.6.6 release.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2019-12-11 15:29 UTC, stp-ip requested changes

2019-12-11 15:29 UTC, stp-ip commented on notes/coredns-1.6.6.md
> +A new plugin [*bufsize*](/plugins/bufsize) has been added to prevents IP fragmentation
```suggestion
 A new plugin [*bufsize*](/plugins/bufsize) has been added that prevents IP fragmentation 
```

2019-12-11 15:29 UTC, stp-ip commented on notes/coredns-1.6.6.md
> +for the DNS Flag Day 2020 and to deal with DNS vulnerability.
```suggestion
for the DNS Flag Day 2020 and to deal with DNS vulnerabilities.
```

2019-12-11 15:29 UTC, stp-ip commented on notes/coredns-1.6.6.md
> +* [*sign*](/plugin/sign) fix signing of authoritative data that are not authoritative for.
```suggestion
* [*sign*](/plugin/sign) fix signing of authoritative data that we are not authoritative for.
```

2019-12-11 15:49 UTC, stp-ip commented
/lgtm

2019-12-11 16:55 UTC, merged

2019-12-12 15:44 UTC, miekg commented
looks good.

I'll kick of a release tomorrow/this evening.

Thanks!