Dedup policy implement between grpc and proxy plugin
miekg/coredns pull request #3537
Opened 2019-12-13 02:24 UTC by zouyee

Signed-off-by: zouyee <zounengren@cmss.chinamobile.com>

### 1. Why is this pull request needed and what does it do?
 `grpc and proxy` plugin  have the same policy implemented  which is worth to  be factored into a couple of common packages .

### 2. Which issues (if any) are related?
a part of https://github.com/coredns/coredns/issues/2695

### 3. Which documentation changes (if any) need to be made?
NONE

### 4. Does this introduce a backward incompatible change or deprecation?
NONE

2019-12-13 11:34 UTC, miekg requested changes
thanks.

dnsutil is probably the wrong package, I suggest pkg/policy and put everything in there

2019-12-16 05:29 UTC, zouyee commented
@miekg PTAL

2019-12-16 07:37 UTC, miekg requested changes

2019-12-16 07:37 UTC, miekg commented on plugin/pkg/policy/policy.go
> +// String return the name of policy Random
```suggestion
// String returns the name of policy Random.
```

2019-12-16 07:37 UTC, miekg commented on plugin/pkg/policy/policy.go
> +// String return the name of policy RoundRobin
```suggestion
// String returns the name of policy RoundRobin.
```

2019-12-16 07:37 UTC, miekg commented on plugin/pkg/policy/policy.go
> +// String return the name of policy Sequential
```suggestion
// String returns the name of policy Sequential.
```

2019-12-17 08:13 UTC, miekg commented
yeah, 50 lines reduction in code :)

2019-12-17 08:13 UTC, miekg commented
/lgtm

2019-12-17 08:15 UTC, merged