Pass the simple communication test result as a pre-condition for ready check
miekg/coredns pull request #3590
Opened 2020-01-13 02:59 UTC by zouyee

### 1. Why is this pull request needed and what does it do?
 Although the connection between coredns and apiserver is broken, but the HasSynced () method  of reflector will not report the error.

If this is "connection refused" error, it means that most likely apiserver is not responsive.
It doesn't make sense to re-list all objects because most likely we will be able to restart watch where we ended.
If that's the case wait and resend watch request.

### 2. Which issues (if any) are related?
https://github.com/coredns/coredns/issues/3587
### 3. Which documentation changes (if any) need to be made?
none
### 4. Does this introduce a backward incompatible change or deprecation?
none

2020-01-13 05:37 UTC, zouyee commented
@miekg PTAL

2020-01-13 06:33 UTC, miekg commented
Good change. Should we extend it more and for instance log the API version
where getting back?

On Mon, 13 Jan 2020, 03:59 Zou Nengren, <notifications@github.com> wrote:

> 1. Why is this pull request needed and what does it do?
>
> Although the connection between coredns and apiserver is broken, but the
> HasSynced () method of reflector will not report the error.
>
> If this is "connection refused" error, it means that most likely apiserver
> is not responsive.
> It doesn't make sense to re-list all objects because most likely we will
> be able to restart watch where we ended.
> If that's the case wait and resend watch request.
> 2. Which issues (if any) are related?
>
> #3587 <https://github.com/coredns/coredns/issues/3587>
> 3. Which documentation changes (if any) need to be made?
>
> none
> 4. Does this introduce a backward incompatible change or deprecation?
>
> none
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/coredns/coredns/pull/3590
> Commit Summary
>
>    - Pass the simple communication test result as a pre-condition for
>    ready check.
>
> File Changes
>
>    - *M* plugin/kubernetes/controller.go
>    <https://github.com/coredns/coredns/pull/3590/files#diff-0> (9)
>
> Patch Links:
>
>    - https://github.com/coredns/coredns/pull/3590.patch
>    - https://github.com/coredns/coredns/pull/3590.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/3590?email_source=notifications&email_token=AACWIW6N6OBZTL6L5WJT4CDQ5PKJLA5CNFSM4KF3UI7KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IFUENDA>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACWIWZWUNSOQG7LVW7HFVLQ5PKJLANCNFSM4KF3UI7A>
> .
>

2020-01-13 13:16 UTC, zouyee commented
@miekg done

2020-01-13 15:21 UTC, miekg requested changes

2020-01-13 15:21 UTC, miekg commented on plugin/kubernetes/controller.go
> +		log.Warningf("While trying to communicate with apiserver found err: %v", err)
```suggestion
		log.Warningf("While trying to communicate with apiserver found error: %v", err)
```

2020-01-13 15:21 UTC, miekg commented on plugin/kubernetes/controller.go
> +	log.Infof("Communication with server successful")
```suggestion
```

2020-01-13 17:31 UTC, chrisohaver commented
Thanks for the PR.  The idea of checking the api connection makes sense.  But more is needed to resolve #3587.

As is, this change will cause the CoreDNS to become unready if the api check fails (assuming the deployment monitors the ready plugin in the readiness probe).  Kubernetes will then stop routing traffic to the unready Pod.  However, it would be left in this unready state indefinitely.

2020-01-13 17:35 UTC, chrisohaver commented
To resolve an issue like #3587,  CoreDNS would need to do one of ...
* re-establish its connection to the API
* exit/die
* report unhealthy such that the Deployment's liveness probe kills it

2020-01-13 18:03 UTC, miekg commented
Unready never goes unhealthy after it becomes healthy. Doing so would lead
to a cascading failure on every network hiccup

On Mon, 13 Jan 2020, 18:31 chrisohaver, <notifications@github.com> wrote:

> Thanks for the PR. The idea of checking the api connection makes sense.
> But more is needed to resolve #3587
> <https://github.com/coredns/coredns/issues/3587>.
>
> As is, this change will cause the CoreDNS to become unready if the api
> check fails (assuming the deployment monitors the ready plugin in the
> readiness probe). Kubernetes will then stop routing traffic to the unready
> Pod. However, it would be left in this unready state indefinitely.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/3590?email_source=notifications&email_token=AACWIW6TN6RVRHAFKXKSNSDQ5SQNVA5CNFSM4KF3UI7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZSWOY#issuecomment-573778747>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACWIW7TFB5MKOMAN2EX34TQ5SQNVANCNFSM4KF3UI7A>
> .
>

2020-01-13 18:12 UTC, johnbelamaric commented
Not sure I follow. All the unready does is remove it from the load balancer
pool, how does that cause a cascading failure? Maybe you mean - CoreDNS /
api server connection lost -> loss of all endpoints in k8s dns -> other
stuff failing? Other than synthetic data plane checks instead of readiness
probes I don't see getting around that.

K8s config also has tolerance built in to prevent transient failures from
cascading - it requires three consecutive readiness probe failures (by
default) in order to go unready.

On Mon, Jan 13, 2020 at 10:03 AM Miek Gieben <notifications@github.com>
wrote:

> Unready never goes unhealthy after it becomes healthy. Doing so would lead
> to a cascading failure on every network hiccup
>
> On Mon, 13 Jan 2020, 18:31 chrisohaver, <notifications@github.com> wrote:
>
> > Thanks for the PR. The idea of checking the api connection makes sense.
> > But more is needed to resolve #3587
> > <https://github.com/coredns/coredns/issues/3587>.
> >
> > As is, this change will cause the CoreDNS to become unready if the api
> > check fails (assuming the deployment monitors the ready plugin in the
> > readiness probe). Kubernetes will then stop routing traffic to the
> unready
> > Pod. However, it would be left in this unready state indefinitely.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/coredns/coredns/pull/3590?email_source=notifications&email_token=AACWIW6TN6RVRHAFKXKSNSDQ5SQNVA5CNFSM4KF3UI7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZSWOY#issuecomment-573778747
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AACWIW7TFB5MKOMAN2EX34TQ5SQNVANCNFSM4KF3UI7A
> >
> > .
> >
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/3590?email_source=notifications&email_token=ACIHRM52DGR7WABWXYCSZELQ5SUF7A5CNFSM4KF3UI7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZV6SI#issuecomment-573792073>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACIHRM2UTJWUKLS7PRE2Z5DQ5SUF7ANCNFSM4KF3UI7A>
> .
>

2020-01-13 18:13 UTC, chrisohaver commented
> Unready never goes unhealthy after it becomes healthy. Doing so would lead
to a cascading failure on every network hiccup

We could add some buffer in the readiness probe, such that it would need to be a long hiccup to trigger it.

2020-01-13 18:15 UTC, chrisohaver commented
> K8s config also has tolerance built in ... it requires three consecutive readiness probe failures.

Ah, the default already has tolerance, makes sense.

2020-01-13 18:15 UTC, miekg commented
No, having them all sync on a shared resource is plain wrong. Adding more
smarts here is also wrong. Caching and forwarding continue to work so there
is no reason to not report readiness true.

On Mon, 13 Jan 2020, 19:13 chrisohaver, <notifications@github.com> wrote:

> Unready never goes unhealthy after it becomes healthy. Doing so would lead
> to a cascading failure on every network hiccup
>
> We could add some buffer in the readiness probe, such that it would need
> to be a long hiccup to trigger it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/3590?email_source=notifications&email_token=AACWIW4BYU77VSYTDXOEWSLQ5SVLLA5CNFSM4KF3UI7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZXBPI#issuecomment-573796541>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACWIW3BIEE3CTRCNR3HDTDQ5SVLLANCNFSM4KF3UI7A>
> .
>

2020-01-13 18:20 UTC, chrisohaver commented
> No, having them all sync on a shared resource is plain wrong. Adding more smarts here is also wrong. Caching and forwarding continue to work so there is no reason to not report readiness true.
> […](#)

The _readiness probe_, in the Kubernetes _Deployment_.  I wasn't suggesting adding buffer into the _ready plugin_.

2020-01-13 18:29 UTC, chrisohaver commented
> To resolve an issue like #3587, CoreDNS would need to do one of ...
> 1. re-establish its connection to the API
> 2. exit/die
> 3.  report unhealthy such that the Deployment's liveness probe kills it

I think a combo of both 1 and 3 would work best... Try to repair the connection, but if that fails for too long, try respawning the Pod.  Not sure of how to best report being "unlive" ... Currently thats per the liveness probe, which points to the health plugin.  Maybe we should point the liveness probe to the ready plugin (with longer tolerance then ready).

2020-01-13 18:34 UTC, johnbelamaric commented
We can just exit. That will be faster than waiting for a probe anyway.

On Mon, Jan 13, 2020 at 10:29 AM chrisohaver <notifications@github.com>
wrote:

> To resolve an issue like #3587
> <https://github.com/coredns/coredns/issues/3587>, CoreDNS would need to
> do one of ...
>
>    1. re-establish its connection to the API
>    2. exit/die
>    3. report unhealthy such that the Deployment's liveness probe kills it
>
> I think a combo of both 1 and 3 would work best... Try to repair the
> connection, but if that fails for too long, try respawning the Pod. Not
> sure of how to best report being "unlive" ... Currently thats per the
> liveness probe, which points to the health plugin. Maybe we should point
> the liveness probe to the ready plugin (with longer tolerance then ready).
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/3590?email_source=notifications&email_token=ACIHRM73SGAGCBEJL4LPZL3Q5SXKJA5CNFSM4KF3UI7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZY6JI#issuecomment-573804325>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACIHRM5FV4MSBM4ETYOA5U3Q5SXKJANCNFSM4KF3UI7A>
> .
>

2020-01-13 18:41 UTC, chrisohaver commented
> We can just exit. That will be faster than waiting for a probe anyway.

I think that _could_ result in many coredns instances going down at the same time during a momentary network outage/glitch that otherwise might have resolved itself.

Tangentially ... are we sure that when the watch dies (as in #3587), that the api server version check fails? Or might it continue to work?

2020-01-13 18:47 UTC, miekg commented
+1

Also how does a watch die? And is HasSynced the only way to notice this?
There must be more trivial ways to restart a watch and/or getting status
back on it?

On Mon, 13 Jan 2020, 19:41 chrisohaver, <notifications@github.com> wrote:

> We can just exit. That will be faster than waiting for a probe anyway.
>
> I think that *could* result in many coredns instances going down at the
> same time during a momentary network outage/glitch that otherwise might
> have resolved itself.
>
> Tangentially ... are we sure that when the watch dies (as in #3587
> <https://github.com/coredns/coredns/issues/3587>), that the api server
> version check fails? Or might it continue to work?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/3590?email_source=notifications&email_token=AACWIW3KK73G3ZMWO4QY65TQ5SYURA5CNFSM4KF3UI7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZ2FTY#issuecomment-573809359>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACWIW7DLVGSJAI2S3P54WTQ5SYURANCNFSM4KF3UI7A>
> .
>

2020-01-13 19:02 UTC, johnbelamaric commented
FWIW, the api server isn't "a single shared resource", in that it should have several replicas running and CoreDNS instances should be randomly connected to different ones, and the backing etcd store is also distributed.

2020-01-13 19:17 UTC, miekg commented
True, but I've seen things go wrong specularly. The point is, coredns is
part of the data plane and you can't just let the control plane decide to
take it down because that's likely the end of your cluster.

On Mon, 13 Jan 2020, 20:02 John Belamaric, <notifications@github.com> wrote:

> FWIW, the api server isn't "a single shared resource", in that it should
> have several replicas running and CoreDNS instances should be randomly
> connected to different ones, and the backing etcd store is also distributed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/3590?email_source=notifications&email_token=AACWIW7VMPFC3TUDDMGFQELQ5S3CVA5CNFSM4KF3UI7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZ4MMY#issuecomment-573818419>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACWIWZ2PGYRMMSGMFWMR6LQ5S3CVANCNFSM4KF3UI7A>
> .
>

2020-01-13 19:18 UTC, chrisohaver commented
> We can just exit. That will be faster than waiting for a probe anyway.

If we do that, then this check should not be in the "ready" path.  I.e. something else that monitors the health of the API connection and dies when it determines the connection is dead.  Is there a watch heartbeat we can monitor?  The watch should be pumping a fairly constant stream of changes to us... If we don't see _anything_ after some time, perhaps we could assume things have gone bad and re-establish the api connection.

2020-01-13 19:18 UTC, yongtang commented
I remember client-go is still not able to connect to multiple api servers natively:
https://github.com/kubernetes/kubernetes/issues/18174

That means some additional work from coredns implementation side if coredns is to handle api server endpoint failures.

2020-01-13 19:20 UTC, chrisohaver commented
> I remember client-go is still not able to connect to multiple api servers natively:
> [kubernetes/kubernetes#18174](https://github.com/kubernetes/kubernetes/issues/18174)
> 
> That means some additional work from coredns implementation side if coredns is to handle api server endpoint failures.

Multiple instances of coredns can connect to different api instances... so there is that redundancy...

2020-01-13 19:37 UTC, johnbelamaric commented
Yeah, understood, but right now K8s doesn't offer data plane checks, only
the control plane checks. I have seen other similar instances of this with
updating the cloud loadbalancer (as opposed to just kube-proxy). So it's a
general class of problem in k8s. Though DNS has a special level of
criticality.

On Mon, Jan 13, 2020 at 11:17 AM Miek Gieben <notifications@github.com>
wrote:

> True, but I've seen things go wrong specularly. The point is, coredns is
> part of the data plane and you can't just let the control plane decide to
> take it down because that's likely the end of your cluster.
>
> On Mon, 13 Jan 2020, 20:02 John Belamaric, <notifications@github.com>
> wrote:
>
> > FWIW, the api server isn't "a single shared resource", in that it should
> > have several replicas running and CoreDNS instances should be randomly
> > connected to different ones, and the backing etcd store is also
> distributed.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/coredns/coredns/pull/3590?email_source=notifications&email_token=AACWIW7VMPFC3TUDDMGFQELQ5S3CVA5CNFSM4KF3UI7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZ4MMY#issuecomment-573818419
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AACWIWZ2PGYRMMSGMFWMR6LQ5S3CVANCNFSM4KF3UI7A
> >
> > .
> >
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/3590?email_source=notifications&email_token=ACIHRM7ZO5CGDDCZYNIY3DLQ5S45HA5CNFSM4KF3UI7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZ6APY#issuecomment-573825087>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACIHRM4TZOUM6HGBJ3LQNPDQ5S45HANCNFSM4KF3UI7A>
> .
>

2020-01-14 02:32 UTC, zouyee commented
> If we do that, then this check should not be in the "ready" path. I.e. something else that monitors the health of the API connection and dies when it determines the connection is dead. 

Regarding the feature of handling connection disconnection, it should be supported by client-go. Readiness probes can be applied in scenarios where applications cannot temporarily provide services. A pod with containers reporting that they are not ready does not receive traffic through Kubernetes Services.

> We can just exit. That will be faster than waiting for a probe anyway.

At the same time, we need to consider the situation of network jitter, so we cannot directly kill the pod.

2020-01-24 10:36 UTC, miekg commented
should we merge this or figure out how we lost  a watch in the first place? I'm more inclined to go for the latter; blindly merging without a root cause doesn't sit well with me

2020-01-24 14:25 UTC, chrisohaver commented
> should we merge this or figure out how we lost a watch in the first place? I'm more inclined to go for the latter; blindly merging without a root cause doesn't sit well with me

I also lean toward not merging until we understand the issue more. I'm not yet convinced that this would fix the problem its aiming to resolve (watch stops receiving updates). It's quite possible that a synchronous query to the API would work fine in this scenario.  E.g. if the reason the watch stops receiving updates is some bug in the api client/server that only affects that watch.

2020-02-24 19:09 UTC, miekg commented
closing here, in favour of learning more about this failure case (which may be in client-go who knows?)

2020-02-24 19:09 UTC, closed without merging