optimize the metrics test
miekg/coredns pull request #3708
Opened 2020-03-02 02:48 UTC by zouyee

Signed-off-by: zouyee <zounyee1989@gmail.com>

### 1. Why is this pull request needed and what does it do?
To optimize the monitoring test, we should not simply confirm the existence of metrics, but compare the results of metrics deeply.

### 2. Which issues (if any) are related?
https://github.com/coredns/coredns/issues/3579

### 3. Which documentation changes (if any) need to be made?
NONE

### 4. Does this introduce a backward incompatible change or deprecation?
NONE

2020-03-02 10:01 UTC, miekg commented
fails travis

2020-03-05 02:08 UTC, zouyee commented
@miekg PTAL

2020-03-06 08:48 UTC, miekg requested changes
this needs to be heavily minimized and only contain the changes that are actually needed

2020-03-06 08:48 UTC, miekg commented on plugin/etcd/etcd.go
> +// which resolve directly. If a TXT record is being resolved by CNAME, then we expect the Host field to have a
unrelated change, please revert

2020-03-06 08:48 UTC, miekg commented on plugin/metrics/metrics.go
> +	ln, err := net.Listen("tcp", m.Addr)
unrelated change, please revert

2020-03-06 08:48 UTC, miekg commented on plugin/test/scrape.go
> +	// DnsMetrics is metrics for dns
```suggestion
	// DnsMetrics contain the metrics we scrape from CoreDNS.
```

2020-03-06 08:48 UTC, miekg commented on plugin/test/scrape.go
> +// NewDnsMetrics returns new metrics which are initialized.
this doesn't look like a very useful function...

2020-03-06 08:48 UTC, miekg commented on plugin/test/scrape.go
> +func GrabDnsMetrics(url string) (DnsMetrics, error) {
```suggestion
func scrape(url string) (DnsMetrics, error) {
```

2020-03-06 08:48 UTC, miekg commented on plugin/test/scrape.go
> +func parseDnsMetrics(data string) (DnsMetrics, error) {
this intermediate function can be removed.

2020-03-06 08:48 UTC, miekg commented on plugin/test/scrape.go
> +func parseMetrics(data string, output *DnsMetrics) error {
parseMetrics should return a DnsMetrics

2020-03-06 08:48 UTC, miekg commented on plugin/test/scrape.go
> +// GetDnsMetrics returns config related metrics from the dns, filtered to t
what's `t`?

2020-03-06 08:48 UTC, miekg commented on plugin/test/scrape.go
> +	// grab Kubelet metrics
comment doesn't match what's done here

2020-03-06 08:48 UTC, miekg commented on plugin/test/scrape.go
> +func NewCacheSample(name model.LabelValue, source model.LabelSet) *model.Sample {
I don't understand the naming here, what's a CacheSample?

2020-03-06 08:48 UTC, miekg commented on test/metrics_test.go
> +	m.SetQuestion("google.com.", dns.TypeA)
use (or don't change www.example.org)

2020-03-06 08:48 UTC, miekg commented on test/metrics_test.go
> +	if diff := cmp.Diff(expect, actual); diff != "" {
cmd.Diff can be handy, but the old test clearly spelled out what was wrong, now this becomes more complex. I like the old way better.

2020-03-06 08:48 UTC, miekg commented on test/metrics_test.go
> +	srv, err := CoreDNSServer(corefile)
this renaming balloons this PR, please don't do that.

2020-07-09 21:16 UTC, miekg commented on plugin/test/scrape.go
> +func parseMetrics(data string, output *DnsMetrics) error {
this is still not done

2020-08-31 08:06 UTC, closed without merging