When no records match, reply with NXDOMAIN
miekg/coredns pull request #377
Opened 2016-11-02 17:48 UTC by chrisohaver

Reply with NXDOMAIN, when there are no matching records.

Addresses issue #357.

2016-11-02 17:54 UTC, miekg requested changes

2016-11-02 17:54 UTC, miekg commented on middleware/kubernetes/handler.go
> +		return middleware.BackendError(&k, zone, dns.RcodeNameError, state, nil /*debug*/, nil, middleware.Options{})
NameErrorr should be handled by the k.IsNameError() above, but k8s already returns `false` for that. I.e. that would be the proper fix.

2016-11-03 13:21 UTC, chrisohaver commented
Reflecting on this change last evening... I think I need to add differentiation between no records, and non-existent domain.

2016-11-03 13:23 UTC, miekg commented on middleware/kubernetes/kubernetes.go
> +	return err == noItemsErr
Is this really the proper way k8s signals nothing found?

2016-11-03 13:23 UTC, miekg commented
well, to be precise, NODATA and NXDOMAIN are two different replies for non-existence.

2016-11-03 13:38 UTC, chrisohaver commented
Yeah - that's what i was referring to in my last comment.

2016-11-05 11:59 UTC, closed without merging