Fix forward policy
miekg/coredns pull request #3901
Opened 2020-05-19 14:01 UTC by martinhaus

### 1. Why is this pull request needed and what does it do?

The policy for selecting upstream servers in the forward plugin is not working properly. Only the first upstream server is always selected no matter which policy is set. The issue seems to occur in 1.6.7 and later.

I changed the way the `List` method in `proxy.go` is used. Instead of passing a slice of structs I converted `[]*Proxy` into `[]interface{}` used the proxy selection method and the converted back to  `[]*Proxy`.

### 2. Which issues (if any) are related?

https://github.com/coredns/coredns/issues/3900

### 3. Which documentation changes (if any) need to be made?

none

### 4. Does this introduce a backward incompatible change or deprecation?

no

2020-05-19 14:18 UTC, chrisohaver commented
Looks like the bug was introduced in PR #3537.  Prior to that, this was a 1 line function.
https://github.com/coredns/coredns/pull/3537/files#diff-b12d06e8aa6117ce05d5715e1c8930c3L191-R197

Not immediately obvious to me why this function was changed in #3537.

2020-05-19 14:33 UTC, chrisohaver commented
I see the same logic in GRPC too, changed in #3537.

2020-05-19 14:46 UTC, chrisohaver reviewed
LGTM, can you add a unit test? Thanks!

2020-05-19 15:58 UTC, martinhaus commented
@chrisohaver I've added the test.

2020-05-19 16:04 UTC, chrisohaver approved these changes
LGTM, thanks!

2020-05-19 16:07 UTC, chrisohaver requested changes
Actually - on second look... something seems off ...  that 2 loops are needed ...

2020-05-19 16:13 UTC, chrisohaver commented
Does the following work?

```
// List returns a set of proxies to be used for this client depending on the policy in f.
func (f *Forward) List() []*Proxy {
	if len(f.p.List(f.proxies)) == 1 {
		return f.p.List(f.proxies)[0].([]*Proxy)
	}
	ps := f.p.List(f.proxies)
	var proxies = make ([]*Proxy, len(ps))
	for i, p := range ps {
		proxies[i] = p.(*Proxy)
	}
	return proxies
}
```

2020-05-19 16:40 UTC, chrisohaver commented
@zouyee, PTAL.

2020-05-19 16:48 UTC, martinhaus commented
No, that does not work.
The problem is related to `List(p ...interface{})` 
https://github.com/coredns/coredns/blob/c9c212703a33ee6588a6b77eed71f2c7fdad577d/plugin/pkg/policy/policy.go#L23

With the configuration pasted in the related issue https://github.com/coredns/coredns/issues/3900, a call to `List` results into getting a slice of slices assigned in `p`.

```
Result of fmt.Println(p) on L24 of `List` (linked above)
[[0xc0001e2a00 0xc0001e2a40 0xc0001e2a80 0xc0001e2ac0]]
```

If you make a request with the snippet you posted above it results in
```
[ERROR] Recovered from panic in server: "dns://:5300"
```

That's why I've added the conversion from []*Proxy into []interface{} and back to resolve this.

2020-05-19 17:42 UTC, chrisohaver commented
> That's why I've added the conversion from []*Proxy into []interface{} and back to resolve this.

Ah - I see... Yes. Perhaps `forward.proxies` should be a slice of non-empty interface that `forward.Proxy` and and `grpc.Proxy` implement.  Either that or make `forward.proxies` and `[]interface{}`, and assert where needed - but that makes it even more opaque.

2020-05-25 10:22 UTC, martinhaus commented
@chrisohaver I'm not sure that'd work. `grpc.Proxy` and `forward.Proxy` do not have a single function in common so I'm not sure how would they be able to implement a non-empty interface.

Also if we add an interface (let's name it `ProxyInteface`) for `forward.Proxy` and make `forward.proxies` a slice of `ProxyInterface` we still cannot pass this to `policy.Sort` as `[]interface{}` without the conversion.

For the second option - making `forward.proxies` a `[]interface{}` and asserting elements everywhere seems like the incorrect approach. 

Maybe changing `policy.List` instead would be a better idea? Or using a separate implementation of the List function for forward and gprc? I'm not sure what would be the correct approach. 

Would do you think?

2020-05-26 11:59 UTC, chrisohaver commented
Since the current behavior is broken, and the proposed fix adds additional processing per request, I'm leaning toward ... 
1. for now, revert #3537 to get this fixed
2. add unit tests to verify the expected behavior (in forward and grpc)
3. then revisit #3537

Owners of forward (@johnbelamaric @miekg @rdrozhdzh), what do you think?

2020-05-29 17:18 UTC, chrisohaver commented
Closing in favor of #3919

2020-05-29 17:18 UTC, closed without merging