Plugin/k8s_ingress
miekg/coredns pull request #3935
Opened 2020-06-08 11:40 UTC by networkop

### 1. Why is this pull request needed and what does it do?
This PR introduces a new `k8s_ingress` plugin to support external resolution of Ingress domain names, similar to what `k8s_external` does for services.

### 2. Which issues (if any) are related?
Issue #2465 

### 3. Which documentation changes (if any) need to be made?
The new plugin readme (part of the PR)
### 4. Does this introduce a backward incompatible change or deprecation?
No, however this would require a new set of RBAC rules, for example:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
  name: excoredns-coredns
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - watch
```

2020-06-08 15:32 UTC, networkop commented
oops, I didn't know there were other CI tests in a separate repo. I'm happy to fix them, once there's a consensus on this PR.

2020-06-09 12:42 UTC, chrisohaver commented
Thanks for the PR! I have not done a full review yet.  Initial thoughts:
* There is a significant amount of code duplication with _k8s_external_. So that has me pause to think on how we could do things differently.  For example, how to more easily allow other plugins to "piggy-back" on the kubernetes API connection.
* This appears to cause the _kubernetes_ plugin to maintain a watch on ingresses, even if _k8s_ingress_ is not in use (i.e. affecting all kubernetes users ).  The Kubernetes scalability team is especially sensitive to bumps in memory, and and pressure on the API server.

2020-06-09 12:54 UTC, networkop commented
Thanks for your feedback!

> * There is a significant amount of code duplication with _k8s_external_. So that has me pause to think on how we could do things differently.  For example, how to more easily allow other plugins to "piggy-back" on the kubernetes API connection.
This is exactly what I thought as well. Not only that, but to make things work between the two plugins, one has to fallthrough to the next when there's no match found, instead of returning zone apex, like [this](https://github.com/coredns/coredns/pull/3935/files#diff-09e5fe140b7035bc7950cfc93ee6555dR107)


> * This appears to cause the _kubernetes_ plugin to maintain a watch on ingresses, even if _k8s_ingress_ is not in use (i.e. affecting all kubernetes users ).  The Kubernetes scalability team is especially sensitive to bumps in memory, and and pressure on the API server.
That is true, and this can be an argument against merging with k8s_external. 
I'm happy to investigate either option.

2020-06-26 10:14 UTC, networkop commented
hi @chrisohaver :wave: 
did you have any further thoughts or feedback on this PR?

2020-06-26 12:07 UTC, chrisohaver commented
> did you have any further thoughts or feedback on this PR?

I'll try to carve out time next week to review it in more detail.

2020-07-09 16:31 UTC, chrisohaver requested changes
@networkop, I spent a few hours going over this.  IMO there is too much code (and comment) duplication for this to be feasibly included as an internal plugin.

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/README.md
> +note the SOA's serial number is static. The IP addresses of the nameserver records are those of the
Static serial: This should probably move to a "Known Issues" section... since its not a desired behavior.

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/README.md
> +CoreDNS service.
> The IP addresses of the nameserver records are those of the CoreDNS service.

The Cluster IP of the service?  For clients outside fo the cluster, this would be an unreachable IP address.

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/README.md
> +Enable names under `example.org` to be resolved to in-cluster DNS addresses.
Can you rephrase this? It doesn't seem to describe what the example does?

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/README.md
> +The plugin uses an external zone to resolve in-cluster IP addresses. It only handles queries for A,
```suggestion
It only handles queries for A,
```

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/README.md
> +Ingresses, similar to what `k8s_external` does for services. This plugin is only useful if the *kubernetes* plugin is also loaded.
```suggestion
This plugin creates records for Kubernetes Ingresses.  This plugin is only useful if the *kubernetes* plugin is also loaded.
```

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/external.go
> +differently). We support A, AAAA and SRV request, for all other types we return NODATA or
SRV records don't appear to be supported in this PR.

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/external.go
> +A plugin willing to provide these services must implement the Externaler interface, although it
Externaler -> Ingresser

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/external.go
> +	// External returns a slice of msg.Services that are looked up in the backend and match
Copy-pasted comments don't match property names in this interface declaration.

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/external.go
> +	//log.Printf("Service query %s", state.Name())
These commented-out debugs should be removed before merging.

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/external.go
> +	// If we did have records, we have to continue to let other plugins pick it up.
missing "not" ? "If we did _not_ have records," ...

This is implicit "fallthrough" behavior, which we should avoid I think.  Instead, add a "fallthough" option to the plugin, and continue down the plugin chain only if fallthough is enabled (see other plugins: kubernetes, hosts).  Also, to be consistent with other fallthrough implementations, we should only be falling through when the result is NXDOMAIN.  e.g. if someone does a TXT query on name that exists, we should return NODATA instead of allowing another plugin to answer.

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/external.go
> +		// TODO(miek): save this in the External struct.
I assume this TODO is copy-pasted?  Does it still apply in this context?

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/external.go
> +/*
Should this file be named `ingress.go`?  is `external.go` a remanent of k8s_external?

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/msg_to_dns.go
> +// not sure if this is even needed.
Please find out, and remove if not needed.

2020-07-09 16:31 UTC, chrisohaver commented on plugin/kubernetes/controller.go
> +	dns.ingLister, dns.ingController = object.NewIndexerInformer(
This informer must be conditionally created, like the pod informer.
When k8s_ingress is not in use, kubernetes should not establish a watch on ingress objects.

2020-07-09 16:31 UTC, chrisohaver commented on plugin/k8s_ingress/README.md
> +AAAA; all others result in NODATA responses. To make it a proper DNS zone, it handles SOA and NS queries for the apex of the zone.
Even though it's implied, probably should call out specifically that PTR requests (reverse lookups) are not handled.

2020-07-09 16:31 UTC, chrisohaver commented on plugin/kubernetes/controller.go
> +	IngIndexReverse(string) []*object.Ingress
This isn't ideal - that we have to modify the controller interface like this.
Perhaps there is another approach...

2020-07-09 16:56 UTC, chrisohaver commented
An alternate approach could be to establish a separate connection and watch on the API.  I think the k8s client-go consolidates connections to minimize overhead.

2020-07-09 21:25 UTC, miekg commented
please send a PR to coredns/coredns.io where this can live as an external plugin. ta.

2020-07-10 09:45 UTC, networkop commented
@chrisohaver thanks for taking time to review this. I also felt there was too much code duplication and changes to other modules/plugins. This was a "naive" implementation where I tried to follow the current plugin (k8s_external) as much as possible. The goal was to open a discussion and get your opinion about what needs to change. So the main two issues with the logic (excluding comments/readme) are:
1. Modifying the k8s controller interface
2. Wrong fallthrough behaviour

I will try to refactor the code to make sure all k8s controller code is pulled into the ingress plugin itself, so it becomes more self-contained. 
However, this still would require changes to RBAC and, consequently, helm charts. So if you think that there's no point in continuing with this PR here, I'm happy work on it externally and, as @miekg suggested, simply list it as one of the external plugins.

2020-07-10 14:30 UTC, chrisohaver commented
The fallthrough behavior is easily fixable.  Avoiding the interface changes less so.  

The k8s controller code is somewhat complex due to a requirement of us keeping under a target memory limit set by Kubernetes.  E.g. we use customized indexer informers and do object conversions. Copying that structure verbatim would carry a lot of bulk and complexity you don't need - you should be able to use the default informers included in client-go.

Another other issue is the "always-on" watch on ingresses, even if k8s_ingress is not enabled in the corefile.
With that always on,  the RBAC rules would need to be updated.  However, if ingresses are only watched if k8s_ingress is enabled, then the RBAC rules only need to permit ingress list/watch when k8s_ingress is enabled.  Since k8s_ingress would not be enabled by default, the RBAC rules don't need to allow it by default.  If a user enables k8s_ingress, they would need to edit the RBAC rules.  This could be described in the README.  In the helm chart, if k8s_ingress is added as a configurable option, then it would need to adjust RBAC rules accordingly.

I think for now this should be an external plugin, and refactored to not require changes to the kubernetes plugin controller interface.

In the future, it would be nice for kubernetes plugin to make the informers/indexers generally available to other plugins (i.e. a way for other plugins to add informer/indexers to the controller or access existing ones).  If we work that out, and k8s_ingress proves to be a popular feature, we can consider integrating it into the tree as an internal plugin.

2020-07-10 14:47 UTC, networkop commented
Understood. I'll close this PR then. I'll update the issue #2465 if/when the external plugin is ready.

2020-07-10 14:47 UTC, closed without merging