Kubernetes Integration Test Cleanup
miekg/coredns pull request #421
Opened 2016-11-10 18:56 UTC by johnbelamaric

Improved the testdata struct to include Rcode and actual RRs.
Now checks Rcode not just counts. Also checks counts. Checking
actual RR values still TODO.

2016-11-10 18:59 UTC, miekg requested changes
Welcome this change, but please use the code that already exists.

2016-11-10 18:59 UTC, miekg commented on test/kubernetes_test.go
> +func makeRR(s string) dns.RR {
test.A and test.MX our your friends here - at least they are used in other tests.

2016-11-10 18:59 UTC, miekg commented on test/kubernetes_test.go
> +var testdata = []testdefn{
There is also infra for this - look at the other tests (can remember from the top of my head which one)

2016-11-10 19:03 UTC, johnbelamaric commented on test/kubernetes_test.go
> +var testdata = []testdefn{
Ack. See that now. Should have checked before I did it!

2016-11-10 20:55 UTC, miekg commented on test/kubernetes_test.go
> +	"github.com/miekg/coredns/middleware/test"
Nit; could you separate these out in coredns import and the rest? So stdlib, coredns, rest?

2016-11-10 20:55 UTC, miekg commented on test/kubernetes_test.go
> +			test.A("mynginx.demo.svc.coredns.local.      1800    IN      A       10.3.0.10"),
For future reference ('cause it is hard to find): a TTL of 303 means: don't check ttl

2016-11-10 20:55 UTC, miekg commented on test/kubernetes_test.go
> +		//TODO: Check the actual RR values
See `test.Section` and `test.Header`

2016-11-12 23:10 UTC, johnbelamaric commented
@chrisohaver already pulled these in when fixing #422 .

2016-11-12 23:10 UTC, closed without merging