middleware/proxy: absorb httpproxy
miekg/coredns pull request #481
Opened 2017-01-15 10:24 UTC by miekg

2017-01-15 13:18 UTC, johnbelamaric commented on middleware/proxy/README.md
> +    protocol [dns [ADDRESS...]|https_google]
What is ADDRESS here?

2017-01-15 13:39 UTC, miekg commented
Will be a thing where you can specify the upstream for resolving
DNS.google.com or /etc/resolved.conf just like other address
specifications. Name could be better

On 15 Jan 2017 1:18 pm, "John Belamaric" <notifications@github.com> wrote:

*@johnbelamaric* commented on this pull request.
------------------------------

In middleware/proxy/README.md
<https://github.com/miekg/coredns/pull/481#pullrequestreview-16714158>:

> @@ -26,7 +26,7 @@ proxy FROM TO... {
     health_check PATH:PORT [DURATION]
     except IGNORED_NAMES...
     spray
-    protocol [dns|https_google]
+    protocol [dns [ADDRESS...]|https_google]

What is ADDRESS here?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/miekg/coredns/pull/481#pullrequestreview-16714158>, or mute
the thread
<https://github.com/notifications/unsubscribe-auth/AAVkW7R4ju_vat4EDLhdaVO4Sy2UUa25ks5rShzBgaJpZM4Lj4V4>
.

2017-01-15 14:50 UTC, johnbelamaric commented
So, you would list protocol twice like this?

```
protocol dns /etc/resolv.conf
protocol https_google
```

That doesn't really make sense to me. What about something like:

```
protocol https_google
bootstrap dns [ADDRESS]
```

or

`protocol https_google bootstrap [ADDRESS]`

if it only applies to https_google (though I suppose it wouldn't).

2017-01-15 18:58 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] middleware/prox..." ]
>So, you would list protocol twice like this?
>
>```
>protocol dns /etc/resolv.conf
>protocol https_google
>```

Why can it be done twice?


>
>```
>protocol https_google
>bootstrap dns [ADDRESS]
>```
>
>or
>
>`protocol https_google bootstrap [ADDRESS]`
>
>if it only applies to https_google (though I suppose it wouldn't).

That's nice syntax. For now I am only adding `https_google`.

/Miek

--
Miek Gieben

2017-01-23 20:00 UTC, miekg commented
Exchanger needs probably to be moved to the staticUpstream and can then be shared between all HostPools

2017-02-06 13:48 UTC, miekg commented
@johnbelamaric @chrisohaver Finally pushed some updates, could you guys give a (2nd) glance over - this could do with some review.
It still needs setup tests, fixing the conflicts and anything else I forgot.

Dropping 400 LOC is not bad though :-)

2017-02-06 16:36 UTC, johnbelamaric requested changes
Looks good overall. Some nits here.

2017-02-06 16:36 UTC, johnbelamaric commented on middleware/proxy/README.md
> +Proxy everything, and re-lookup `dns.google.com` every 30 seconds using the resolvers specified
30 or 300?

2017-02-06 16:36 UTC, johnbelamaric commented on middleware/proxy/README.md
> +  receives a debug queries (i.e. the name is prefixed with `o-o.debug.` a TXT record with Comment
s/queries/query/

2017-02-06 16:36 UTC, johnbelamaric commented on middleware/proxy/README.md
> +  receives a debug queries (i.e. the name is prefixed with `o-o.debug.` a TXT record with Comment
Also missing closing paren after `o-o.debug.`.

2017-02-06 16:36 UTC, johnbelamaric commented on middleware/proxy/README.md
> -* `spray` when all backends are unhealthy, randomly pick one to send the traffic to. (This is a failsafe.)
Are you removing this feature?

2017-02-06 16:36 UTC, johnbelamaric commented on middleware/proxy/README.md
> +Proxy everything, and re-lookup `dns.google.com` every 30 seconds using the resolvers specified
README says 300

2017-02-06 17:46 UTC, miekg commented on middleware/proxy/README.md
> -* `spray` when all backends are unhealthy, randomly pick one to send the traffic to. (This is a failsafe.)
No, $editor foobar. Fixed.

2017-02-06 17:47 UTC, johnbelamaric commented on middleware/proxy/google.go
> +	fmt.Printf("new hosts %v\n", hosts)
remove debug

2017-02-06 17:48 UTC, miekg commented
Thanks. All done. I'll add some more tests.

2017-02-06 18:10 UTC, johnbelamaric approved these changes

2017-02-06 18:26 UTC, miekg commented
I'll merge as-is and fixup the tests in later PRs

2017-02-06 19:32 UTC, merged