WIP: Add field keywords to rewrite middleware
miekg/coredns pull request #497
Opened 2017-01-31 18:24 UTC by bwaz

Add field keywords to the rewrite middleware. First handled keyword will be edns0. Without a keyword used the NewSimpleRule Rule will be used. Logic for handling edns0 will come soon. 

We can add "simple" as well to be backwards compatible.

2017-01-31 21:29 UTC, miekg reviewed
I agree with the direction we're going here. The only thing I would ask is to be mindful of the language:
1. extensibility  
2. uniformity with the rest of coredns

2017-01-31 21:29 UTC, miekg commented on middleware/rewrite/field.go
> +// NewFieldRule creates a new Field Rule
Nit: needs closing dot.

2017-01-31 21:29 UTC, miekg commented on middleware/rewrite/field.go
> +	switch field {
bogus function body because WIP?

2017-01-31 21:29 UTC, miekg commented on middleware/rewrite/setup.go
> +func NewRule(args []string) Rule {
Docs

2017-02-02 18:59 UTC, bwaz commented
@miekg  @johnbelamaric  
Init work, edns0 or any other keywords can be added in a new PR
This change makes field a requirement.

2017-02-03 07:30 UTC, miekg commented on middleware/rewrite/README.md
> +e.g., to rewrite ANY queries to HINFO, use `rewrite qtype ANY HINFO`.
think we should rename qtype to just `type`, we also just use `class`

2017-02-03 07:31 UTC, miekg commented on middleware/rewrite/README.md
> +Additional FIELD keywords may be implemented to support more rewrite use-cases.
This more of a package level documention then something for a readme. Think this readme's should be focused on usage

2017-02-03 07:34 UTC, miekg commented on middleware/rewrite/rewrite.go
> +	// init
init -> `New returns a new rule.`

2017-02-03 07:34 UTC, miekg reviewed
lgtm - modulo some nits. I'll update the 005 release wiki

2017-02-03 07:37 UTC, miekg commented on middleware/rewrite/README.md
> +e.g., to rewrite ANY queries to HINFO, use `rewrite qtype ANY HINFO`.
and type as well?

2017-02-03 07:38 UTC, miekg commented on middleware/rewrite/rewrite_test.go
> +			Fields["qname"].New("from.nl.", "to.nl."),
We should try to use `example.*` zone in these tests (yes, there is a of `miek.nl` and `.nl` out there still)

2017-02-06 13:34 UTC, bwaz commented on middleware/rewrite/README.md
> +e.g., to rewrite ANY queries to HINFO, use `rewrite qtype ANY HINFO`.
I'll change it to class, type, name

2017-02-06 14:21 UTC, bwaz commented on middleware/rewrite/rewrite_test.go
> +			Fields["qname"].New("from.nl.", "to.nl."),
I'm having an issue with testing *
```
diff --git a/middleware/rewrite/rewrite_test.go b/middleware/rewrite/rewrite_test.go
index ffb1b4a..63d2f84 100644
--- a/middleware/rewrite/rewrite_test.go
+++ b/middleware/rewrite/rewrite_test.go
@@ -20,9 +20,10 @@ func TestRewrite(t *testing.T) {
        rw := Rewrite{
                Next: middleware.HandlerFunc(msgPrinter),
                Rules: []Rule{
-                       Fields["qname"].New("from.nl.", "to.nl."),
+                       Fields["name"].New("from.nl.", "to.nl."),
+                       Fields["name"].New("myexample.*", "myexample.com."),
                        Fields["class"].New("CH", "IN"),
-                       Fields["qtype"].New("ANY", "HINFO"),
+                       Fields["type"].New("ANY", "HINFO"),
                },
                noRevert: true,
        }
@@ -35,6 +36,7 @@ func TestRewrite(t *testing.T) {
                toT   uint16
                toC   uint16
        }{
+               {"myexample.org.", dns.TypeA, dns.ClassINET, "myexample.com.", dns.TypeA, dns.ClassINET},
                {"from.nl.", dns.TypeA, dns.ClassINET, "to.nl.", dns.TypeA, dns.ClassINET},
                {"a.nl.", dns.TypeA, dns.ClassINET, "a.nl.", dns.TypeA, dns.ClassINET},
                {"a.nl.", dns.TypeA, dns.ClassCHAOS, "a.nl.", dns.TypeA, dns.ClassINET},

```

```
--- FAIL: TestRewrite (0.00s)
	rewrite_test.go:61: Test 0: Expected Name to be 'myexample.com.' but was 'myexample.org.'

```

2017-02-06 14:28 UTC, bwaz commented on middleware/rewrite/rewrite_test.go
> +			Fields["qname"].New("from.nl.", "to.nl."),
Anything I'm doing wrong with the setup?

2017-02-06 16:41 UTC, johnbelamaric requested changes
Looking good.

2017-02-06 16:41 UTC, johnbelamaric commented on middleware/rewrite/README.md
> +When the FIELD is `type` and FROM is (`A`, `MX`, etc.), the type of the message will be rewriten;
s/rewriten/rewritten/

2017-02-06 16:41 UTC, johnbelamaric commented on middleware/rewrite/README.md
>  the first rewrite is applied.
Is this true? Is this what we want? If you can specify multiple re-write middleware, then I assume they all act independently.

2017-02-06 16:41 UTC, johnbelamaric commented on middleware/rewrite/setup.go
> +			}
else return an error so the user knows they made a typo...

2017-02-06 19:15 UTC, miekg commented on middleware/rewrite/README.md
>  the first rewrite is applied.
It can be done, but it fairly useless, because clients reject responses that are fiddled with, also DNSSEC...

2017-02-06 19:19 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] Add field keywo..." ]
>bwaz commented on this pull request.
>
>
>
>> @@ -20,9 +20,9 @@ func TestRewrite(t *testing.T) {
> 	rw := Rewrite{
> 		Next: middleware.HandlerFunc(msgPrinter),
> 		Rules: []Rule{
>-			NewSimpleRule("from.nl.", "to.nl."),
>-			NewSimpleRule("CH", "IN"),
>-			NewSimpleRule("ANY", "HINFO"),
>+			Fields["qname"].New("from.nl.", "to.nl."),
>
>I'm having an issue with testing *
>```
>diff --git a/middleware/rewrite/rewrite_test.go b/middleware/rewrite/rewrite_test.go
>index ffb1b4a..63d2f84 100644
>--- a/middleware/rewrite/rewrite_test.go
>+++ b/middleware/rewrite/rewrite_test.go
>@@ -20,9 +20,10 @@ func TestRewrite(t *testing.T) {
>        rw := Rewrite{
>                Next: middleware.HandlerFunc(msgPrinter),
>                Rules: []Rule{
>-                       Fields["qname"].New("from.nl.", "to.nl."),
>+                       Fields["name"].New("from.nl.", "to.nl."),
>+                       Fields["name"].New("myexample.*", "myexample.com."),
>                        Fields["class"].New("CH", "IN"),
>-                       Fields["qtype"].New("ANY", "HINFO"),
>+                       Fields["type"].New("ANY", "HINFO"),
>                },
>                noRevert: true,
>        }
>@@ -35,6 +36,7 @@ func TestRewrite(t *testing.T) {
>                toT   uint16
>                toC   uint16
>        }{
>+               {"myexample.org.", dns.TypeA, dns.ClassINET, "myexample.com.", dns.TypeA, dns.ClassINET},
>                {"from.nl.", dns.TypeA, dns.ClassINET, "to.nl.", dns.TypeA, dns.ClassINET},
>                {"a.nl.", dns.TypeA, dns.ClassINET, "a.nl.", dns.TypeA, dns.ClassINET},
>                {"a.nl.", dns.TypeA, dns.ClassCHAOS, "a.nl.", dns.TypeA, dns.ClassINET},
>
>```
>
>```
>--- FAIL: TestRewrite (0.00s)
>	rewrite_test.go:61: Test 0: Expected Name to be 'myexample.com.' but was 'myexample.org.'
>
>```

Oh, yeah, this might not work, because you're doing multiple rules chained after
each other (unless you fixed that as well). At least in CoreDNS <= 004 this
chaining never worked.

2017-02-06 19:46 UTC, bwaz commented
I suggest splitting any additional work from this point to new PR

2017-02-06 19:55 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] Add field keywo..." ]
>I suggest splitting any additional work from this point to new PR

ack.

2017-02-07 15:51 UTC, johnbelamaric approved these changes

2017-02-07 15:52 UTC, johnbelamaric commented
lgtm

2017-02-07 21:53 UTC, merged