middleware/proxy: Allow non-HTTP upstreams to be health checked
miekg/coredns pull request #589
Opened 2017-03-14 15:36 UTC by mfischer-zd

Allow HTTP health check to be performed against a regular DNS upstream server.

TODO: Add tests.

2017-03-14 15:58 UTC, mfischer-zd commented
@miekg Need a bit of help with the test design.  Is there a recommended miekg/dns analogue to net/http/httptest?

2017-03-14 16:36 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/pr..." ]
>@miekg Need a bit of help with the test design.  Is there a recommended miekg/dns analogue to net/http/httptest?

Integration tests are put in toplevel test/ dir.

There is a dnsrecorder: middleware/pkg/dnsrecorder

/Miek

--
Miek Gieben

2017-03-14 16:58 UTC, mfischer-zd commented
@miekg I'm not sure dnsrecorder is what I'm looking for.  I'd like to amend the `TestHealthCheck()` function in middleware/proxy/upstream_test.go, which gets its host list from the `testPool()` function, which is defined in middleware/proxy/policy_test.go.

So I think I want to instantiate a mock upstream DNS server in `TestMain()` in the policy_test.go file.

2017-03-14 17:08 UTC, miekg commented
If you need a DNS server that replies to something the easiest way to do that is just to start a coredns server, but those tests that do that are all in tests/ (mostly to get around cyclic deps and have some sanity with the imports)

2017-03-15 23:39 UTC, mfischer-zd commented
Tests added and ready for review.

2017-03-15 23:57 UTC, miekg requested changes
Thanks! Some nits, but looks good.

2017-03-15 23:57 UTC, miekg commented on middleware/proxy/upstream.go
> +	"os"
nit: this needs to be sorted above.

2017-03-15 23:57 UTC, miekg commented on middleware/proxy/upstream.go
> +			fmt.Fprintf(os.Stderr, "Health check probe failed: %v\n", err)
don't think this adds anything

2017-03-15 23:57 UTC, miekg commented on test/proxy_http_health_test.go
> +	"io"
sorting

2017-03-15 23:57 UTC, miekg commented on test/proxy_http_health_test.go
> +	"github.com/miekg/dns"
sorting: std lib first, then coredns, then the rest.

2017-03-15 23:57 UTC, miekg commented on test/proxy_http_health_test.go
> +	log.SetOutput(ioutil.Discard)
Nit: put this at the top of the function.

2017-03-16 00:21 UTC, mfischer-zd commented on middleware/proxy/upstream.go
> +			fmt.Fprintf(os.Stderr, "Health check probe failed: %v\n", err)
If an upstream ends up out of rotation due to a failing health check, having the check failures logged would be useful in performing root cause analysis. 

I couldn't find a more generic log infrastructure, other than the error logging middleware - and this is a warning, not an error.  Can you suggest a better way to deliver this diagnostic information to the user?

2017-03-16 00:27 UTC, mfischer-zd commented
Updated imports per feedback.

2017-03-16 00:28 UTC, mfischer-zd commented on test/proxy_http_health_test.go
> +	"github.com/miekg/dns"
Fixed.

2017-03-16 07:24 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/pr..." ]
>mfischer-zd commented on this pull request.
>
>
>
>>  		if r, err := http.Get(hostURL); err == nil {
> 			io.Copy(ioutil.Discard, r.Body)
> 			r.Body.Close()
> 			host.Unhealthy = r.StatusCode < 200 || r.StatusCode >= 400
> 		} else {
>+			fmt.Fprintf(os.Stderr, "Health check probe failed: %v\n", err)
>
>If an upstream ends up out of rotation due to a failing health check, having the check failures logged would be useful in performing root cause analysis.
>
>I couldn't find a more generic log infrastructure, other than the error logging middleware - and this is a warning, not an error.  Can you suggest a better way to deliver this diagnostic information to the user?

Ack. Just use `log.Printf` with '[WARNING]'

2017-03-16 21:02 UTC, mfischer-zd commented
Updated per feedback.

2017-03-16 21:10 UTC, miekg approved these changes

2017-03-16 21:10 UTC, merged

2017-03-16 21:35 UTC, miekg commented
Hmmm, I was a bit to quick :/ But we def. need to fix that data race.

2017-03-16 21:38 UTC, mfischer-zd commented
Sorry, which data race?

2017-03-16 21:43 UTC, miekg commented
travis just failed, I can reproduce locally
~~~
==================
WARNING: DATA RACE
Read at 0x00c420309658 by goroutine 104:
  github.com/coredns/coredns/middleware/proxy.NewStaticUpstreams.func1.1()
      /home/miek/g/src/github.com/coredns/coredns/middleware/proxy/upstream.go:91 +0x53
  github.com/coredns/coredns/middleware/proxy.(*UpstreamHost).Down()
      /home/miek/g/src/github.com/coredns/coredns/middleware/proxy/proxy.go:73 +0xd6
  github.com/coredns/coredns/middleware/proxy.(*staticUpstream).Select()
      /home/miek/g/src/github.com/coredns/coredns/middleware/proxy/upstream.go:288 +0x3e7
  github.com/coredns/coredns/middleware/proxy.Proxy.ServeDNS()
      /home/miek/g/src/github.com/coredns/coredns/middleware/proxy/proxy.go:97 +0x254
  github.com/coredns/coredns/middleware/proxy.(*Proxy).ServeDNS()
      <autogenerated>:12 +0xec
  github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS()
      /home/miek/g/src/github.com/coredns/coredns/core/dnsserver/server.go:190 +0xab9
  github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket.func1()
      /home/miek/g/src/github.com/coredns/coredns/core/dnsserver/server.go:88 +0xb9
  github.com/miekg/dns.HandlerFunc.ServeDNS()
      /home/miek/g/src/github.com/miekg/dns/server.go:84 +0x51
  github.com/miekg/dns.(*Server).serve()
      /home/miek/g/src/github.com/miekg/dns/server.go:579 +0x80c

Previous write at 0x00c420309658 by goroutine 28:
  github.com/coredns/coredns/middleware/proxy.(*staticUpstream).healthCheck()
      /home/miek/g/src/github.com/coredns/coredns/middleware/proxy/upstream.go:253 +0x28f
  github.com/coredns/coredns/middleware/proxy.(*staticUpstream).HealthCheckWorker()
      /home/miek/g/src/github.com/coredns/coredns/middleware/proxy/upstream.go:272 +0x84

Goroutine 104 (running) created at:
  github.com/miekg/dns.(*Server).serveUDP()
      /home/miek/g/src/github.com/miekg/dns/server.go:533 +0x38c
  github.com/miekg/dns.(*Server).ActivateAndServe()
      /home/miek/g/src/github.com/miekg/dns/server.go:400 +0x420
  github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket()
      /home/miek/g/src/github.com/coredns/coredns/core/dnsserver/server.go:92 +0x20d
  github.com/mholt/caddy.startServers.func1()
      /home/miek/g/src/github.com/mholt/caddy/caddy.go:672 +0xfc

Goroutine 28 (running) created at:
  github.com/coredns/coredns/middleware/proxy.NewStaticUpstreams()
      /home/miek/g/src/github.com/coredns/coredns/middleware/proxy/upstream.go:109 +0xa5d
  github.com/coredns/coredns/middleware/proxy.setup()
      /home/miek/g/src/github.com/coredns/coredns/middleware/proxy/setup.go:18 +0x72
  github.com/mholt/caddy.executeDirectives()
      /home/miek/g/src/github.com/mholt/caddy/caddy.go:583 +0x794
  github.com/mholt/caddy.ValidateAndExecuteDirectives()
      /home/miek/g/src/github.com/mholt/caddy/caddy.go:533 +0x4e2
  github.com/mholt/caddy.startWithListenerFds()
      /home/miek/g/src/github.com/mholt/caddy/caddy.go:437 +0x7b
  github.com/mholt/caddy.Start()
      /home/miek/g/src/github.com/mholt/caddy/caddy.go:429 +0x14d
  github.com/coredns/coredns/test.CoreDNSServer()
      /home/miek/g/src/github.com/coredns/coredns/test/server.go:26 +0x185
  github.com/coredns/coredns/test.TestProxyWithHTTPCheckOK()
      /home/miek/g/src/github.com/coredns/coredns/test/proxy_http_health_test.go:68 +0x541
  testing.tRunner()
      /home/miek/upstream/go/src/testing/testing.go:657 +0x107
==================
--- FAIL: TestProxyWithHTTPCheckOK (0.01s)
	testing.go:610: race detected during execution of test
FAIL
exit status 1
FAIL	github.com/coredns/coredns/test	10.196s
~~~

2017-03-16 21:45 UTC, mfischer-zd commented
Oh, Travis failed for a different reason, I noticed.  Looks like URL.Port() is new for Go 1.8.  Do you want me to port back to 1.7, or make Travis test against 1.8?

2017-03-16 21:48 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/pr..." ]
>Oh, Travis failed for a different reason, I noticed.  Looks like URL.Port() is new for Go 1.8.  Do you want me to port back to 1.7, or make Travis test against 1.8?

Having 1.7 works as well would be nice (should document that). I.e current, and
last version of Go are supported.

2017-03-16 21:48 UTC, mfischer-zd commented
Stand by for PR to fix both.

2017-03-16 22:28 UTC, mfischer-zd commented
Fix in #603