Padding and pinning
miekg/coredns pull request #623
Opened 2017-04-18 13:00 UTC by yawn

PR for https://github.com/coredns/coredns/issues/540

**NOT** ready for review yet.

2017-04-18 18:51 UTC, johnbelamaric commented
Convention is to put WIP (work in progress) in front if it's not ready for review.

2017-06-01 17:13 UTC, miekg commented
We should still review this, no?

2017-06-01 17:14 UTC, yawn commented
Yep :-)
Miek Gieben <notifications@github.com> schrieb am Do. 1. Juni 2017 um 19:13:

> We should still review this, no?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/623#issuecomment-305559502>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AABHQu6hxzU7NAjpztvPSDWDCCgFZVfxks5r_vE1gaJpZM4NAT2t>
> .
>

2017-06-01 17:43 UTC, miekg requested changes
Thanks for the PR, look useful.

2017-06-01 17:43 UTC, miekg commented on middleware/proxy/README.md
> +      pinset 0uXWIwuNdaaFSx7xJySymocwKDFJeEVzlouiy6MZATA=
pinset seems not to be used and even if we need it (I don't know what it is), it should be in another PR.

2017-06-01 17:43 UTC, miekg commented on middleware/proxy/README.md
> +    fixed length of 255 minus the length of the name
drop "fixed" here and end the sentence with a dot.

2017-06-01 17:43 UTC, miekg commented on middleware/proxy/padding.go
> +	return &Padding{
Why all this? You just want to base64 encode some random string? I.e. `sync.Pool`?

2017-06-01 17:43 UTC, miekg commented on middleware/proxy/padding.go
> +	if padding < 1 {
Why this? According to https://developers.google.com/speed/public-dns/docs/dns-over-https padding makes the request the same size. So even if the name is 255 chars long we can still have padding if we make each message (say) 400 bytes.

2017-06-01 17:43 UTC, miekg commented on middleware/proxy/padding.go
> +	if padding < 1 {
Think it makes sense to pad everything to 300 bytes no matter what.

2017-06-01 17:43 UTC, miekg commented on middleware/proxy/padding.go
> +	buf := p.buffers.Get().(*bytes.Buffer)
Ah, here is where you use the buffers... Is there a possibility to do this without all this buffer handling? Seems like overkill (but I could be wrong).

2017-06-01 17:43 UTC, miekg commented on middleware/proxy/padding.go
> +// Generate produces an appropriatep adding string for the given name
needs closing dot and has typo in it.

2017-07-24 21:40 UTC, miekg commented
are you still working on this?

2017-07-26 08:07 UTC, miekg commented
closing this, please re-open if you want to start working on it again.

2017-07-26 08:07 UTC, closed without merging

2017-08-16 13:16 UTC, yawn commented
Complete lack of time currently, sorry