Handle K8s middleware NS record
miekg/coredns pull request #662
Opened 2017-05-05 20:45 UTC by chrisohaver

Adds NS record for the dns service name and ip.
For an NS query: The service domain name (per k8s dns spec), and the service's Cluster IP are returned.
Also, an A record request for "ns.dns.zone" will return the service's Cluster IP. (to make the SOA response valid)

2017-05-06 03:19 UTC, johnbelamaric requested changes
Also you need to go fmt.

2017-05-06 03:19 UTC, johnbelamaric commented on middleware/kubernetes/kubernetes.go
> +	if state.Name() == DefaultNSName+"."+r.zone && state.Type() == "A" {
Do we really need to do the additions with "." and r.zone or can we just do strings.Index(state.Name(), DefaultNSName) == 0 ?

2017-05-06 08:37 UTC, miekg requested changes

2017-05-06 08:37 UTC, miekg commented on middleware/kubernetes/kubernetes.go
> +	if state.Name() == DefaultNSName+"."+r.zone && state.Type() == "A" {
`DefaultNSName` could also include a `.`

Also: shall we move some of this logic on another file? This one getting big, `ns.go` or something?

2017-05-06 08:37 UTC, miekg commented on middleware/kubernetes/kubernetes.go
> +type nsRecord struct {
Can't we just use `dns.A`?

2017-05-06 08:37 UTC, miekg commented on middleware/kubernetes/kubernetes.go
> +func (k *Kubernetes) CoreDNSRecord() nsRecord {
Can there only be 1?

2017-05-08 14:01 UTC, chrisohaver commented on middleware/kubernetes/kubernetes.go
> +func (k *Kubernetes) CoreDNSRecord() nsRecord {
Realistically/Practically, yes.  Which is why I treat it this way.

In theory, there could be multiple services pointing to the coredns pod, and those services may or may not have the DNS port open.  So a complete answer would be to look at each service that points to the pod, and examine the port forwarding in the service and pod configs to see which ones forward dns to coredns.

But in this PR, I am assuming there is one service for the DNS pod, and that service forwards DNS port to the pod.

2017-05-08 20:35 UTC, chrisohaver commented on middleware/kubernetes/kubernetes.go
> +	if state.Name() == DefaultNSName+"."+r.zone && state.Type() == "A" {
@johnbelamaric : `strings.Index(state.Name(), DefaultNSName) == 0` would falsely catch an A record request for `ns.dns.svc.cluster.local`... which could be a valid domain name for service "ns" in  namespace "dns".

2017-05-09 08:52 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Handle K8s mi..." ]
>chrisohaver commented on this pull request.
>
>
>
>> @@ -92,13 +101,27 @@ func (k *Kubernetes) Services(state request.Request, exact bool, opt middleware.
> 		return nil, nil, e
> 	}
>
>+	if state.Name() == DefaultNSName+"."+r.zone && state.Type() == "A" {
>
>@johnbelamaric : `strings.Index(state.Name(), DefaultNSName) == 0` would falsely catch an A record request for `ns.dns.svc.cluster.local`... which could be a valid domain name for service "ns" in  namespace "dns".

ah, we also claiming a namespace here. Should we rename 'dns' to
'kube-system'?

Is `r.zone` static, 'cause the above causes garbage for every query hitting this
middleware.

2017-05-09 13:24 UTC, chrisohaver commented
> ah, we also claiming a namespace here. Should we rename 'dns' to 'kube-system'?

Ideally, SOA would return the actual domain name of the dns service.  But currently, backend_lookup SOA returns a hard-coded record to `ns.dns.[zone]`, which means that all middleware needs to add handle an A record request for `ns.dns.[zone]`.

> Is `r.zone` static, 'cause the above causes garbage for every query hitting this middleware.

r.zone can be different for each request. A middleware can handle more then one zone, each request is only for one zone.

2017-05-09 13:30 UTC, johnbelamaric commented
Still, we can do the Index check and then double-check inside the if with the complete string. That way we avoid the garbage *unless* we enter the if - it's somewhat unlikely that we will see a service named `ns` in a namespace `dns`.

Or maybe we should change the `dns.dns.` hardcoding.

2017-05-09 13:36 UTC, chrisohaver commented
> Or maybe we should change the dns.dns. hardcoding.

Yes, IMO we should change SOA to ask the middleware what the record should be... ideally in a way that doest require us to update all other middleware.

2017-05-09 15:22 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Handle K8s mi..." ]
>> ah, we also claiming a namespace here. Should we rename 'dns' to 'kube-system'?
>
>Ideally, SOA would return the actual domain name of the dns service.  But currently, backend_lookup SOA returns a hard-coded record to `ns.dns.[zone]`, which means that all middleware needs to add handle an A record request for `ns.dns.[zone]`.
>
>> Is `r.zone` static, 'cause the above causes garbage for every query hitting this middleware.
>
>r.zone can be different for each request. A middleware can handle more then one zone, each request is only for one zone.

Ack. but we should try to do this with allocating a new string

2017-05-11 21:34 UTC, chrisohaver commented
Latest change ...
* Splits NS record functions into a separate file: ns.go
* Reduces heap allocations per kubernetes middleware query. Based on compile time escape analysis - not run time profiling.

2017-05-11 21:38 UTC, johnbelamaric commented on Makefile.release
> +DOCKER:=chrisohaver
This file shouldn't be included in the PR.

2017-05-11 21:39 UTC, johnbelamaric commented on Makefile
> +check: deps
this file shouldn't be in here either

2017-05-11 21:45 UTC, chrisohaver commented on Makefile
> +check: deps
ugh... i wonder what else snuck in... My intent was to only commit ns.go and kubernetes.go

2017-05-11 22:55 UTC, chrisohaver commented
Looking into the pod lookup related integration test failures.
Pod lookups (both insecure and verified) work when i do manual testing in a real k8s deployment.
Not yet sure why it fails in travis integration.

2017-05-11 23:05 UTC, chrisohaver commented on Makefile
> +check: deps
OK - mystery solved... at some point I accidentally dropped the "docker" target off a  `make -f Makefile.release docker` command ...
`make -f Makefile.release` automatically does a `git commits -am"Release $(VERSION)"` ...

2017-05-12 01:05 UTC, johnbelamaric commented
Ah ha!

2017-05-12 06:59 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Handle K8s mi..." ]
>chrisohaver commented on this pull request.
>
>
>
>> @@ -15,7 +15,7 @@ deps: core/zmiddleware.go core/dnsserver/zdirectives.go
> 	go get -u github.com/golang/lint/golint
>
> .PHONY: check
>-check: fmt deps
>+check: deps
>
>OK - mystery solved... at some point I accidentally dropped the "docker" target off a  `make -f Makefile.release docker` command ...
>`make -f Makefile.release` automatically does a `git commits -am"Release $(VERSION)"` ...

Ai, that's worth fixing

2017-05-15 22:33 UTC, johnbelamaric commented
@miekg any thoughts on this comment from earlier:

>> ah, we also claiming a namespace here. Should we rename 'dns' to 'kube-system'?

>Ideally, SOA would return the actual domain name of the dns service. But currently, backend_lookup SOA returns a hard-coded record to ns.dns.[zone], which means that all middleware needs to add handle an A record request for ns.dns.[zone].

I think that's the only outstanding question here.

2017-05-16 09:54 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Handle K8s mi..." ]
>@miekg any thoughts on this comment from earlier:
>
>>> ah, we also claiming a namespace here. Should we rename 'dns' to 'kube-system'?
>
>>Ideally, SOA would return the actual domain name of the dns service. But currently, backend_lookup SOA returns a hard-coded record to ns.dns.[zone], which means that all middleware needs to add handle an A record request for ns.dns.[zone].
>
>I think that's the only outstanding question here.

I think we should not claim another namespace and default to kube-system as that
would interfere least with the rest of the system? WDYT?

2017-05-16 13:39 UTC, chrisohaver commented
I think the PR is fine as is in this regard.

`dns` is not a valid object type (valid types are `svc` or `pod`), so there is no chance of namespace collision. `myservice.ns.dns.[zone].` cannot reference a valid kubernetes service.

The only trouble that the hard coded SOA response presents is that every middleware has to implement/handle an A record for that static entry.  This is already added for K8s (in this PR).  The dns service will have two A records...
- one at `ns.dns.zone.`
- the other typically at `kube-dns.kube-system.svc.zone.` 

The PTR record points to `kube-dns.kube-system.svc.zone.`

2017-05-16 14:22 UTC, johnbelamaric commented
Ok, so from a k8s perspective there isn't really an issue here. `ns.dns.cluster.local.` doesn't conflict with any other record that k8s middleware should handle. @miekg from a DNS perspective is there an issue with the PTR not pointing to the A record that matches the SOA?

I think we probably just need a separate issue to discuss/decide whether we want CoreDNS to hard code the SOA name and force an A record with that name.

2017-05-16 14:30 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Handle K8s mi..." ]
>Ok, so from a k8s perspective there isn't really an issue here. `ns.dns.cluster.local.` doesn't conflict with any other record that k8s middleware should handle. @miekg from a DNS perspective is there an issue with the PTR not pointing to the A record that matches the SOA?

Ok. Let's use 'dns'. Nothing should check a PTR to a SOA's MNAME (I think)

>I think we probably just need a separate issue to discuss/decide whether we want CoreDNS to hard code the SOA name and force an A record with that name.

Yes.

2017-05-16 14:32 UTC, johnbelamaric approved these changes

2017-05-19 17:12 UTC, johnbelamaric commented
@miekg I think this is ready - it doesn't hit the diff coverage number because of improvements to code that is tested by the integration but would require mocking the API to cover it in UT.

2017-05-19 17:13 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Handle K8s mi..." ]
>@miekg I think this is ready - it doesn't hit the diff coverage number because of improvements to code that is tested by the integration but would require mocking the API to cover it in UT.

Ack. I'll give it a review in ~2 hours

2017-05-22 08:44 UTC, miekg reviewed
Looks good, some nits and comments.

2017-05-22 08:44 UTC, miekg commented on middleware/kubernetes/controller.go
> +type dnsControllerItf interface {
Naming: Drop the Itf and just leave it as `dnsController` and rename the type below to `dnsControl`

2017-05-22 08:44 UTC, miekg commented on middleware/kubernetes/kubernetes.go
> +	if qtype == "NS" {
Most dns type comparisons use dns.TypeXX (`dns.TypeNS`), how did we end up with a string here?

2017-05-22 08:44 UTC, miekg commented on middleware/kubernetes/ns.go
> +func (k *Kubernetes) DefaultNSMsg(r recordRequest) msg.Service {
Do these methods all need to be exported?

2017-05-22 08:44 UTC, miekg commented on middleware/kubernetes/ns.go
> +func (k *Kubernetes) DoCoreDNSRecord(ifAddrs ifAddrsFunc) dns.A {
Drop the `Do' and lowercase `Core`.

Why the `CoreDNSRecord()` -> `DoCoreDNSRecord` indirection? `DoCoreDNSRecord` is useful by itself?

2017-05-22 13:41 UTC, chrisohaver commented on middleware/kubernetes/ns.go
> +func (k *Kubernetes) DoCoreDNSRecord(ifAddrs ifAddrsFunc) dns.A {
That was for quick and dirty stubbing.  I have replaced it with a more idiomatic struct wrapper and interface.

2017-05-22 13:44 UTC, chrisohaver commented on middleware/kubernetes/controller.go
> +type dnsControllerItf interface {
I did consider naming the interface dnsControllerer. :wink:

2017-05-22 14:17 UTC, miekg approved these changes

2017-05-22 14:18 UTC, miekg commented
Test fail, pasting here because I just took a look:
~~~
--- FAIL: TestKubernetesIntegrationFallthrough (1.04s)
	kubernetes_test.go:436: Expected rcode 0 but got 2 for query cluster.local., 2
	kubernetes_test.go:440: Expected 1 answers but got 0 for query cluster.local., 
~~~

2017-05-22 20:05 UTC, merged