Add k8s external service CNAMEs
miekg/coredns pull request #677
Opened 2017-05-26 22:00 UTC by chrisohaver

- `CNAME` requests: `CNAME` records are returned for all k8s services pointing to an external name  
- `A` requests for k8s external services: `CNAME` record returned in addition to an `A` record for the`CNAME` target. `A` record retrieved from upstream server
- Add `upstream` option to k8s middleware config.
- Unit test and Integration tests
- Minor refactoring of msg.HostType(): Change TypeANY return code to TypeCNAME. I think TypeCNAME maps more logically to a host containing a name.
- Updated k8s middleware README

This doesn't yet handle SRV requests for external services.  I'd prefer to defer that to a later PR, if we determine it's needed.

2017-05-26 22:45 UTC, chrisohaver commented
Looks like hyperkube version of k8s doesn't support external name services.
I use minikube with a newer k8s locally to test integrations.

2017-05-26 23:28 UTC, chrisohaver commented
Yeah - Looks like the ExternalName service type was added in kubernetes 1.4, and travis is using kubernetes 1.3.8.  Looking into how to update...

2017-05-27 00:38 UTC, chrisohaver commented
Tried a couple of 1.6 versions, they never started successfully.
Landed on 1.5, which works, but requires port spec declarations for externalname services (not required in 1.6).
Added port spec declarations... build tests passed.

2017-05-29 11:12 UTC, johnbelamaric approved these changes

2017-05-29 11:14 UTC, johnbelamaric requested changes
Actually, one little thing. Since this feature was (inadvertently) left out of the 1.0.0 DNS schema spec, the TXT record should be changed to return 1.0.1. See https://github.com/kubernetes/dns/pull/89

2017-05-29 11:59 UTC, johnbelamaric approved these changes
You're up early 😀

2017-05-30 12:20 UTC, merged