middleware/kubernetes: Implement current federation beta
miekg/coredns pull request #723
Opened 2017-06-08 21:26 UTC by chrisohaver

This implements cross-cluster service discovery of federated services.
When querying CoreDNS for an A record of a federated service, coredns first checks the local cluster.  

- If the service is present and healthy, CoreDNS returns an A record for the service.  
- If the service is not present or unhealthy, CoreDNS returns a CNAME record for the service in the federated format (e.g. service.namespace.federationname.svc.availibility-zone.region.domain). Also included in the response is the CNAME chain and A record from the upstream server.

2017-06-08 21:50 UTC, miekg requested changes

2017-06-08 21:50 UTC, miekg commented on middleware/kubernetes/federation_test.go
> +func (apiConnFedTest) Run() {
nit: you put these 1-line function on 1 line, even without newlines between them.

2017-06-08 21:50 UTC, miekg commented on middleware/kubernetes/README.md
> +	# federation <federation-name> <federation-domain>
This whole readme needs proper docs or more expansion (this is not relevant to this PR, just saying)

2017-06-08 21:50 UTC, miekg commented on middleware/kubernetes/controller.go
> +func newdnsController(kubeClient *kubernetes.Clientset, resyncPeriod time.Duration, lselector *labels.Selector, initPodCache bool, initNodeCache bool) *dnsControl {
These bools needs to be backed in an Opts struct, then this function can use just an Opt parameter where these bools are fields in

2017-06-08 21:50 UTC, miekg commented on middleware/kubernetes/controller.go
> +	nodeList, _ := dns.nodeLister.List()
why disregard the return error?

2017-06-08 21:50 UTC, miekg commented on middleware/kubernetes/federation.go
> +	// But importing above breaks coredns with flag collision of 'log_dir'
we don't have `log_dir`, maybe glog does? We already remove `log_dir` from coredns' flags.

2017-06-08 21:50 UTC, miekg commented on middleware/kubernetes/federation.go
> +// federation CNAMRecord returns a service record for the requested federated service
federationCNAMERercord

2017-06-08 21:50 UTC, miekg commented on middleware/kubernetes/federation.go
> +		break
what's this `break`? We only range for the first element?

2017-06-08 22:34 UTC, chrisohaver commented on middleware/kubernetes/federation.go
> +		break
We range until we find a node with non-empty region and availability-zone labels.
This mimics the kube-dns kludge.  The break is there for the unlikely case that the federation name in the request doesn't match a federation in the config, we don't bother checking other nodes.

2017-06-08 22:45 UTC, chrisohaver commented on middleware/kubernetes/controller.go
> +func newdnsController(kubeClient *kubernetes.Clientset, resyncPeriod time.Duration, lselector *labels.Selector, initPodCache bool, initNodeCache bool) *dnsControl {
which params do you think should go in it?
just the two bools? or also the resyncPeriod and label selector?

2017-06-08 22:50 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ku..." ]
>chrisohaver commented on this pull request.
>
>
>
>> @@ -67,7 +70,7 @@ type dnsControl struct {
> }
>
> // newDNSController creates a controller for CoreDNS.
>-func newdnsController(kubeClient *kubernetes.Clientset, resyncPeriod time.Duration, lselector *labels.Selector, initPodCache bool) *dnsControl {
>+func newdnsController(kubeClient *kubernetes.Clientset, resyncPeriod time.Duration, lselector *labels.Selector, initPodCache bool, initNodeCache bool) *dnsControl {
>
>which params do you think should go in it?
>just the two bools? or also the resyncPeriod and label selector?

just start with the bools, we can always do more if we want to, but it starts
a pattern which will be good.

/Miek

--
Miek Gieben

2017-06-08 22:51 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ku..." ]
>chrisohaver commented on this pull request.
>
>
>
>> +			if f.name != r.federation {
>+				continue
>+			}
>+			if r.endpoint == "" {
>+				return msg.Service{
>+					Key:  strings.Join([]string{msg.Path(r.zone, "coredns"), r.typeName, r.federation, r.namespace, r.service}, "/"),
>+					Host: strings.Join([]string{r.service, r.namespace, r.federation, r.typeName, node.Labels[LabelAvailabilityZone], node.Labels[LabelRegion], f.zone}, "."),
>+				}
>+			}
>+			return msg.Service{
>+				Key:  strings.Join([]string{msg.Path(r.zone, "coredns"), r.typeName, r.federation, r.namespace, r.service, r.endpoint}, "/"),
>+				Host: strings.Join([]string{r.endpoint, r.service, r.namespace, r.federation, r.typeName, node.Labels[LabelAvailabilityZone], node.Labels[LabelRegion], f.zone}, "."),
>+			}
>+
>+		}
>+		break
>
>We range until we find a node with non-empty region and availability-zone labels.
>This mimics the kube-dns kludge.  The break is there for the unlikely case that the federation name in the request doesn't match a federation in the config, we don't bother checking other nodes.

ack. Slight comments above the `break` that says this?

2017-06-08 22:51 UTC, chrisohaver commented on middleware/kubernetes/README.md
> +	# federation <federation-name> <federation-domain>
Regarding visual formatting: I can move in-line comments into separate sections.
Can you point to an example README format that I should follow.

Regarding expansion: What areas need expansion/improvement? Federation I presume, and others...

2017-06-09 01:16 UTC, chrisohaver commented on middleware/kubernetes/kubernetes.go
> +	k.APIConn = newdnsController(kubeClient, k.ResyncPeriod, k.Selector, k.PodMode == PodModeVerified, true)
oops...

2017-06-09 01:40 UTC, chrisohaver commented on middleware/kubernetes/federation.go
> +	// But importing above breaks coredns with flag collision of 'log_dir'
It may be unvendored glog conflicting with vendored glog.
We may need to vendor k8s.io/apimachinery

2017-06-09 01:42 UTC, chrisohaver commented on middleware/kubernetes/README.md
> +	# federation <federation-name> <federation-domain>
Let's track this in a separate issue...

2017-06-09 09:18 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ku..." ]
>chrisohaver commented on this pull request.

I see:
~~~
./coredns flag redefined: log_dir
panic: ./coredns flag redefined: log_dir
~~~
that's pretty shit :(

/Miek

--
Miek Gieben

2017-06-09 18:34 UTC, chrisohaver commented
Regarding the latest commit to the PR.  I decided to implement the node lookup the "right way" instead of mimicking the kube-dns kludge.  We now pull the availability Zone and Region from the Node that coredns actually resides in (not just the first node in the cluster). It's also more efficient this way, doesn't require a watch on node objects.

2017-06-09 19:21 UTC, johnbelamaric requested changes
I think you can pull that snippet out. Otherwise, LGTM.

2017-06-09 19:21 UTC, johnbelamaric commented on middleware/kubernetes/controller.go
> +
Since you went to the one-time lookup, we don't need this anymore.

2017-06-09 19:45 UTC, johnbelamaric approved these changes

2017-06-10 18:26 UTC, chrisohaver commented on middleware/kubernetes/README.md
> +	# federation <federation-name> <federation-domain>
I've created #728 to track this issue.

2017-06-11 22:11 UTC, miekg commented on middleware/kubernetes/federation.go
> +	// But importing above breaks coredns with flag collision of 'log_dir'
Checked this, indeed annoying :(

2017-06-11 22:11 UTC, miekg approved these changes

2017-06-14 13:38 UTC, merged