Middleware/Kubernetes: Add RR check to K8s integration tests
miekg/coredns pull request #884
Opened 2017-08-10 15:50 UTC by rajansandeep

Added the RR checks to Kubernetes integration test as per issue #831.

2017-08-10 15:57 UTC, chrisohaver commented on test/kubernetes_test.go
> -// +build k8s
Dont remove this line, its a build constraint ... see https://golang.org/pkg/go/build/
It is used by the make file to control when this test is executed.

2017-08-10 17:16 UTC, chrisohaver commented
The test failures are due to dynamic allocation of pod IPs in k8s.  i.e. Pod IPs different on your system than on the Travis system.  This breaks the headless services tests, since headless services answer with the pod IPs for the service (they don't have a virtual cluster IP).

You could replace the "expected" results for the headless services with a function call that looks up the endpoints (pods), for the service by escaping to shell and running `kubectl` ... or by connecting ot the API (`kubectl` probably easier).  For example

```
Answer: getEndpoints("headless-svc", "test-1")

```

where getEndpoints returns `[]dns.RR` ... one for each endpoint under the service/namespace passed.

2017-08-10 17:33 UTC, chrisohaver commented
Some `kubectl` magic to get the IPs ...

`kubectl -n test-1 get endpoints headless-svc -o 'jsonpath={.subsets[*].addresses[*].ip}'`

2017-08-10 19:43 UTC, miekg requested changes
How are the test results established, just running kube-dns and using those results? Or running CoreDNS?

I rather see that this PR also *decreases* the number of tests while keeping the same coverage. `go test -coverage` is a very useful tool for that.

2017-08-10 19:43 UTC, miekg commented on test/kubernetes_test.go
>  		Qname: "bogusendpoint.svc-1-a.test-1.svc.cluster.local.", Qtype: dns.TypeA,
Can we also add a little comment above each of these of *what* it actually tests?

2017-08-10 19:43 UTC, miekg commented on test/kubernetes_test.go
> +		Qname: "bogusservice.any.svc.cluster.local.", Qtype: dns.TypeA,
can we also test longer names than this?

2017-08-10 19:43 UTC, miekg commented on test/kubernetes_test.go
> +		Qname: "svc-1-a.test-1.svc.cluster.local.", Qtype: dns.TypeA,
What new code paths are tested by these? Do the increase the go coverage?

2017-08-10 20:04 UTC, miekg commented
We should probably also check other record types, HINFO (to name one) and NS for instance.

2017-08-10 20:04 UTC, chrisohaver commented on test/kubernetes_test.go
> +		Qname: "svc-1-a.test-1.svc.cluster.local.", Qtype: dns.TypeA,
The added test case are not new test cases, they are test case that have two different answers based on the coredns configuration.

2017-08-10 20:05 UTC, chrisohaver commented
> We should probably also check other record types, HINFO (to name one) and NS for instance.

Sure, In interest to keep this PR from running away, open a issue to add those.

2017-08-10 20:07 UTC, chrisohaver commented on test/kubernetes_test.go
> +		Qname: "bogusservice.any.svc.cluster.local.", Qtype: dns.TypeA,
Yes - perhaps we should add an issue to expand test cases in integration tests.  This PR is focused on adding response record validation.

2017-08-10 20:49 UTC, miekg commented
Ok, but just in the interested of keeping the amount of work done low - we might want to cut back on the amount now, instead of fixing each and everyone right now and then deleting a bunch of them later?

2017-08-10 20:52 UTC, chrisohaver commented
> How are the test results established, just running kube-dns and using those results? Or running CoreDNS?

> I rather see that this PR also decreases the number of tests while keeping the same coverage. go 

Where are you seeing that?

> test -coverage is a very useful tool for that.

I think it's `go test -cover` ...

But not sure what value actually counts coverage for in this case.  It's an integration test that in some cases runs multiple instances of coredns (one main, and one upstream server).   It looks like its only counting coverage for the setting up of the test and the sending of queries.  The actually tests cases are executed against instances of coredns, which are not tracked by test coverage... So as is, the coverage numbers are useless here.  As far as I can tell.

2017-08-10 20:56 UTC, chrisohaver commented
> Ok, but just in the interested of keeping the amount of work done low - we might want to cut back on the amount now, instead of fixing each and everyone right now and then deleting a bunch of them later?

Why would we be deleting tests?

2017-08-10 21:03 UTC, miekg commented
This tests establishes that any and * are equivalent:
~~~
svc-1-a.*.svc.cluster.local.
svc-1-a.any.svc.cluster.local.
~~~
What does this test test?
~~~
bogusservice.*.svc.cluster.local.
bogusservice.any.svc.cluster.local.
~~~

We should delete tests that don't add any coverage

2017-08-10 21:15 UTC, chrisohaver commented
> We should delete tests that don't add any coverage

Ideally - yes.  The risk is removing tests that we think don't add coverage, but actually do.

We can remove tests where its obvious - i.e. redundant wildcard checks.

2017-08-10 21:20 UTC, miekg commented
Indeed. That's why adding a rational above each test as comment would make sense. It forces you to think about these issues. More tests != better testing.

Also: one big question that I have is left unanswered: how we do validate the results? Is this compared with kube-dns? Do we have a doc outlining the differences and why ?

2017-08-10 21:25 UTC, chrisohaver commented
> Also: one big question that I have is left unanswered: how we do validate the results? Is this compared with kube-dns? 

They are validated per the k8s spec, which kube-dns also follows.
However, some functions, such as wildcards, don't have kube-dns equivalents.

> Do we have a doc outlining the differences and why ?

No.

2017-08-10 22:38 UTC, miekg commented
> They are validated per the k8s spec, which kube-dns also follows.
> However, some functions, such as wildcards, don't have kube-dns equivalents.

Interesting, do you have example of those?

2017-08-11 13:40 UTC, chrisohaver commented
> Interesting, do you have example of those?

Any feature we support but kube-dns does not.  I thought wildcard queries was one... perhaps I am mistaken.  Queries that use features like autopath, pods verified mode, fall into the same category.
I think fallthough also.  However I think as of k8s 1.6, kube-dns supports fallthrough-like behavior.

2017-08-11 14:02 UTC, johnbelamaric commented
I don't think they do `fallthrough` like behavior, but they do allow you to configure stub zones in the dnsmasq configuration, which works similarly to doing different server blocks for those domains to go to different upstreams in CoreDNS.

2017-08-15 15:02 UTC, miekg commented on test/kubernetes_test.go
> +		sort.Sort(test.RRSet(tc.Answer))
I don't think we need to sort the testcases as well.

2017-08-15 15:03 UTC, miekg commented on test/kubernetes_test.go
> +	println(cmd_str)
Left over debugging?

2017-08-15 15:05 UTC, miekg commented on test/kubernetes_test.go
> +			test.CNAME("ext-svc.test-1.svc.cluster.local. 0 IN	CNAME	example.net."),
This TTL is really low... Is that intentional?

2017-08-15 15:07 UTC, miekg commented on test/kubernetes_test.go
> +			test.TXT("dns-version.cluster.local. 28800 IN TXT \"1.0.1\""),
If you use "`" (backtacks) you are use raw strings in Go, no need to escape the " in the TXT rdata.

2017-08-15 15:07 UTC, chrisohaver commented on test/kubernetes_test.go
> +	println(cmd_str)
I updated the title with WIP, to reflect that this is a work in progress.

Sandeep is debugging a travis vs local environment issue at the moment, so he is committing changes to the PR to debug on travis.  i.e. yes - it is debug...

2017-08-15 15:09 UTC, miekg commented on test/kubernetes_test.go
>  		Rcode:  dns.RcodeNameError,
This Rcode is wrong; this should be dns.RcodeSucccess and the message reply should indicate a nodata reponse.

2017-08-15 15:11 UTC, miekg requested changes
Yes, I think there is no other choice than `getDynamicEndpoints` and calling `kubectl`. I do note however that we are pinning ourselves to specific `kubect` output which may lead to a lot of churn in the future.

2017-08-15 15:13 UTC, chrisohaver commented
>  I do note however that we are pinning ourselves to specific kubect output which may lead to a lot of churn in the future.

Not really - the command gets json data (which is the same fields as the API).  So not nearly as bad as parsing human readable command line output.

2017-08-15 15:21 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] WIP: Middlewa..." ]
>>  I do note however that we are pinning ourselves to specific kubect output which may lead to a lot of churn in the future.
>
>Not really - the command gets json data (which is the same fields as the API).  So not nearly as bad as parsing human readable command line output.

Ah cool, I stand correct. nice!

2017-08-15 15:25 UTC, chrisohaver commented on test/kubernetes_test.go
> +			test.CNAME("ext-svc.test-1.svc.cluster.local. 0 IN	CNAME	example.net."),
just set the TTL to 303...

2017-08-15 15:31 UTC, chrisohaver commented on test/kubernetes_test.go
> +			test.CNAME("ext-svc.test-1.svc.cluster.local. 0 IN	CNAME	example.net."),
Actually - most of these should be 303... (which I believe is secret handshake for dont check the TTL)...

We might want to put more thought into what the TTLs should be later.

2017-08-15 16:28 UTC, chrisohaver commented on test/kubernetes_test.go
> +		// Before sorting, make sure that CNAMES do not appear after their target records
This can be made into a function and put in test.  e.g. test.CNAMEOrder(res.Answer)

2017-08-15 16:48 UTC, rajansandeep commented on test/kubernetes_test.go
> +		sort.Sort(test.RRSet(tc.Answer))
That means we have to sort the testcases manually?

2017-08-15 16:56 UTC, chrisohaver requested changes

2017-08-15 16:56 UTC, chrisohaver commented on test/kubernetes_test.go
> +		// Before sorting, make sure that CNAMES do not appear after their target records
This CNAME answer order check can be made into a function and put in middleware/test/helpers.go. e.g. test.CNAMEOrder(res.Answer).

2017-08-15 19:48 UTC, chrisohaver requested changes

2017-08-15 19:48 UTC, chrisohaver commented on middleware/test/helpers.go
>  // Function to make sure that CNAMES do not appear after their target records
It's good practice to make the comment before a method start with the method name.  For example:

`// CNAMEOrder makes sure that CNAMES do not appear after their target records`

2017-08-15 19:54 UTC, chrisohaver approved these changes

2017-08-16 06:31 UTC, miekg commented on test/kubernetes_test.go
> +			test.CNAME("ext-svc.test-1.svc.cluster.local. 0 IN	CNAME	example.net."),
Yes 303 is special, obscurely documented some where :-)

2017-08-16 06:33 UTC, miekg commented
I wanted to raise the following point
With this PR we moving away from having our test data in version control, as there is now this dynamic component. This is a *big* change that surely impacts debugging.

Why does this need to be dynamic? Because of the difference between minikube and Travis? Why are those different? How can we make them less different?

2017-08-16 13:10 UTC, chrisohaver commented
> With this PR we moving away from having our test data in version control, as there is now this dynamic component. 

The only dynamic aspect is the IP address in the response records.  The other parts of those response records are hard coded (i.e. in version control). So, yes, the IPs are dynamic, but all other aspects of the response are not.

>Why does this need to be dynamic? Because of the difference between minikube and Travis? Why are those different? How can we make them less different?

The dynamic nature is not a difference between minikube and hyperkube.  In this regard, they both behave the same way.  The reason for the dynamic assignment is due to how kubernetes assigns IPs to pods.  Kubernetes (not just minikube or hyperkube) assigns IPs to pods dynamically from a pool.

I dont think the dynamic IPs in tests is a problem.  And I think retrieving the IPs for the pods is the right approach.  Nevertheless, some alternatives...
* Reserve a special IP to mean "don't compare this IP" ... similar to TTL 303. Then we can skip comparing the IP in these dynamic records.  This is the same as not testing the IPs at all. It provides less coverage.
* Hard code the IPs in the tests to the answers we get in the Travis environment.  Since we are nuking the environment every time, the IPs might be the same every time.  However, this isn't a guarantee - we would be relying on race conditions.  Also, it would cause test failures in local instances, since those systems will have other pods for testing (the pool isn't the same state).

2017-08-16 15:16 UTC, miekg commented
Thanks for the update; yes those alternative are bad as well. With ample t.Logf this is probably the best we can do.

2017-08-16 15:18 UTC, miekg commented on test/kubernetes_test.go
> +		sort.Sort(test.RRSet(tc.Answer))
tc does not need to be sorted.

2017-08-16 15:20 UTC, miekg commented on test/kubernetes_test.go
> +	result := strings.Split(getCmdOutput(name, namespace), " ")
Go style is usualy to omit **get**, so just `cmdOutput`

2017-08-16 15:21 UTC, miekg commented on test/kubernetes_test.go
> +	len_result := len(result)
Err... @chrisohaver told me we parse the json from kubectl, here we just string split the output?

2017-08-16 15:22 UTC, miekg commented on test/kubernetes_test.go
> +		println(os.Stderr, "There was an error running kubectl command: ", err.Error())
Don't use `println`: return the error and neatly log the failures from the caller so it is clear what went wrong.

2017-08-16 15:23 UTC, miekg commented on test/kubernetes_test.go
> +	len_result := len(result)
I should probably also run
`cmdArgs := kctl + " -n " + name + " get endpoints " + namespace + " -o jsonpath={.subsets[*].addresses[*].ip}"`
to see what this output, 'cause I don't now what happens if you specify a json path

2017-08-16 15:23 UTC, miekg commented on test/kubernetes_test.go
> +func getDynamicEndpoints(Qname, namespace, name string) []dns.RR {
Document this function was some example inputs

2017-08-16 15:25 UTC, miekg commented on test/kubernetes_test.go
> +	if len_result > 1 {
Underscore names is not idiomatic go, just use `l`, or `lr`

2017-08-16 15:26 UTC, miekg commented on test/kubernetes_test.go
> +			ip := strings.Replace(result[i], ".", "-", -1)
don't we have a kubernetes helper function for this?

2017-08-16 15:26 UTC, miekg commented on test/kubernetes_test.go
> +func getSRVrecords(Qname, Qtype, namespace, name string) []dns.RR {
Document this function and drop the `get`

2017-08-16 15:27 UTC, miekg commented on test/kubernetes_test.go
> +	if len_result > 1 {
Revert the flow here:
`len_result == 1 {
 // ip stuff
return
}
// srv stuff

2017-08-16 15:28 UTC, miekg commented on test/kubernetes_test.go
> +		println(os.Stderr, "There was an error running kubectl command: ", err.Error())
Short documentation for the function would help as well.

2017-08-16 15:29 UTC, miekg commented on test/kubernetes_test.go
> +	return string(cmdOut)
The `bytes` pkg has almost all operations the string package has, there is no need to convert this into a `string`.

2017-08-16 15:39 UTC, chrisohaver commented on test/kubernetes_test.go
> +	len_result := len(result)
> @chrisohaver told me we parse the json from kubectl, here we just string split the output?

It's splitting output produced by the json path filter.

> I don't now what happens if you specify a json path

It depends on what path you give it. In this case, the path will list all IPs for each endpoint.

2017-08-16 15:44 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] WIP: Middlewa..." ]
>chrisohaver commented on this pull request.
>
>
>
>> @@ -479,8 +840,63 @@ func TestKubernetesIntegrationFallthrough(t *testing.T) {
> 	drop 0
>     }
> `
>-	cases := append(dnsTestCases, dnsTestCasesFallthrough...)
>-	doIntegrationTests(t, corefile, cases)
>+	doIntegrationTests(t, corefile, dnsTestCasesFallthrough)
>+}
>+
>+func getDynamicEndpoints(Qname, namespace, name string) []dns.RR {
>+	rr := []dns.RR{}
>+
>+	result := strings.Split(getCmdOutput(name, namespace), " ")
>+	len_result := len(result)
>
>> @chrisohaver told me we parse the json from kubectl, here we just string split the output?
>
>It's splitting output produced by the json path filter.
>
>> I don't now what happens if you specify a json path
>
>It depends on what path you give it. In this case, the path will list all IPs for each endpoint.

Yeah, updated my comment. This function can however be improved with some 
documentation.

2017-08-16 19:04 UTC, rajansandeep commented on test/kubernetes_test.go
> +		println(os.Stderr, "There was an error running kubectl command: ", err.Error())
What is the most idiomatic way to report an error when you're not in a test. This error would occur during the declaration of the global variable.

2017-08-16 21:24 UTC, chrisohaver commented
I think more descriptive names for CmdOutput, SRVRecords, and DynamicEndpoints could be...

`kubectlGetEndpointIPs` ... or maybe just `endpointIPs`
`headlessAResponse`
`headlessSRVResponse`

They are longer, but more descriptive of what the methods do.
Also, I don't think the methods need to be exported, so they should start with lower case letters.

2017-08-17 07:19 UTC, miekg commented on test/kubernetes_test.go
> +		println(os.Stderr, "There was an error running kubectl command: ", err.Error())
You "bubble up" the error to the caller, which may handle the error, but calling log.Fatal or t.Fatal. So in this case the function should return a tuple of `[]byte, errror` and not log anything by itself.

2017-08-17 11:14 UTC, miekg commented on test/kubernetes_test.go
> +//headlessAResponse returns the answer to an A request for the specific name and namespace
Thanks for adding comments. You don't need to formally describe the input params this should be obvious from the function signature. Function comments should read like a short story. I.e. `godoc .` in this dir should be a "nice read"

2017-08-17 11:15 UTC, miekg reviewed
This is starting to look good. A few small things and then this can be merged.

2017-08-17 20:38 UTC, rajansandeep commented
One integration test is failing due to issue #808

2017-08-18 13:25 UTC, chrisohaver commented
I think the `SRV` test for `*.svc-1-a.test-1.svc.cluster.local.` have the wrong expected value.  It should _not_ be expecting a `NODATA`, rather it should be expecting a `NOERROR`, with the all of the SRV records for that service.  All of the following `SRV` queries should have the same answer...
* `svc-1-a.test-1.svc.cluster.local.` 
* `*.svc-1-a.test-1.svc.cluster.local.`
* `*.*.svc-1-a.test-1.svc.cluster.local.`

...One minor difference being the question in each answer record would match the original question.... but all other parts should be identical.

2017-08-18 13:33 UTC, chrisohaver commented
> I think the `SRV` test for `*.svc-1-a.test-1.svc.cluster.local.` has the wrong expected results...

That said, even after correcting the results, the test will still fail, due to #808

2017-08-18 13:49 UTC, miekg commented on middleware/test/helpers.go
> +func CNAMEOrder(t *testing.T, res *dns.Msg) bool {
Why does this return a boolean as the t.Errorf is already done in the function?

2017-08-18 13:51 UTC, miekg commented on test/kubernetes_test.go
> +		sort.Sort(test.RRSet(tc.Answer))
Can you add a comment here on why this is needed?

2017-08-18 13:51 UTC, miekg approved these changes
Left two small nits.

2017-08-18 14:25 UTC, chrisohaver commented on test/kubernetes_test.go
> +			test.SRV("svc-1-a.test-1.svc.cluster.local.	303	IN	SRV	0 50 443 svc-1-a.test-1.svc.cluster.local."),
The answers should (I think), have the question in them ... e.g. 
`test.SRV("svc-1-a.test-1.svc.cluster.local.	303	IN	SRV	0 50 443 svc-1-a.test-1.svc.cluster.local.")`
should instead be ...
`test.SRV("*.svc-1-a.test-1.svc.cluster.local.	303	IN	SRV	0 50 443 svc-1-a.test-1.svc.cluster.local.")`

2017-08-23 06:55 UTC, miekg commented
What's the status here? There are a few conflicts in kubernetes.go that don't look too bad. 

I also want to tackle https://github.com/coredns/coredns/issues/942 but that should wait on this PR other it will create a whole bunch of conflicts

2017-08-23 13:00 UTC, chrisohaver commented
> What's the status here? 

Approved, waiting for you to merge. But looks like the PR has to be rebased again.

2017-08-23 16:56 UTC, miekg commented
Is this failure the issue @chrisohaver just opened? #975 ?
~~~
--- FAIL: TestKubernetesIntegration (3.03s)
	helpers.go:179: rr 0 should have a Target of "svc-1-a.test-1.svc.cluster.local.", but has "172-17-0-4.svc-1-a.test-1.svc.cluster.local."
	helpers.go:296: ;; opcode: QUERY, status: NOERROR, id: 5997
		;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
		
		;; QUESTION SECTION:
		;*.svc-1-a.test-1.svc.cluster.local.	IN	 SRV
		
		;; ANSWER SECTION:
		*.svc-1-a.test-1.svc.cluster.local.	0	IN	SRV	0 50 443 172-17-0-4.svc-1-a.test-1.svc.cluster.local.
		*.svc-1-a.test-1.svc.cluster.local.	0	IN	SRV	0 50 80 172-17-0-4.svc-1-a.test-1.svc.cluster.local.
		
		;; ADDITIONAL SECTION:
		172-17-0-4.svc-1-a.test-1.svc.cluster.local.	0	IN	A	172.17.0.4
~~~

2017-08-23 17:04 UTC, chrisohaver commented
> Is this failure the issue @chrisohaver just opened?

Yes, to the 2nd item in #975. Actually coredns responds with an `NXDOMAIN` which breaks this test. The same way kube-dns responds.  And the test used to expect `NXDOMAIN` ...

2017-08-23 17:08 UTC, chrisohaver commented
> Yes, to the 2nd item in #975. 

No, I'm wrong, related to, but not caused by the 3rd Item in #975...

But the failure is that we are getting a wrong answer here.  The answer and extra sections point to the service endpoint (wrong IP ).

2017-08-23 17:20 UTC, chrisohaver commented
Ah - i see whats going on...  There is query ambiguity..

The * in that position can either mean "any `_protocol`"  or "any `endpoint`" ... but we have no way of knowing what the intent was.

The expected value in the test is the answer for ""all `_protocol`"" in service `svc-1-a`
The coredns response is for "all `endpoint`" in service `svc-1-a`

So - the coredns behavior may be correct - if we decide thats how we want it to behave.

This is why kube-dns answers queries like `_tcp.svc-1-a .test-1.svc.cluster.local` as `NXDOMAIN`... because it's treading the `_tcp` as an endpoint... which is the correct answer.

2017-08-23 17:29 UTC, miekg commented
> This is why kube-dns answers queries like _tcp.svc-1-a .test-1.svc.cluster.local as NXDOMAIN... because it's treading the _tcp as an endpoint... which is the correct answer.

Ok we should change that then.

2017-08-24 14:53 UTC, chrisohaver commented
@miekg , OK to merge?

2017-08-24 15:01 UTC, miekg commented
Yes, if there are no failing tests.

On Aug 24, 2017 3:54 PM, "chrisohaver" <notifications@github.com> wrote:

> @miekg <https://github.com/miekg> , OK to merge?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/884#issuecomment-324659401>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAVkW3_Pr7tm_K__w-E5P5FSA-bPfLzVks5sbY6CgaJpZM4OzoCA>
> .
>

2017-08-24 15:05 UTC, merged