mw/kubernetes: remove zone from parseRequest
miekg/coredns pull request #938
Opened 2017-08-18 18:05 UTC by miekg

State has the zone info as well, so don't need to have it in
parseRequest anymore.

2017-08-18 19:32 UTC, miekg commented
I'll double check why test coverage is going down. Could be just the deleted lines.

2017-08-18 20:29 UTC, chrisohaver requested changes

2017-08-18 20:29 UTC, chrisohaver commented on middleware/kubernetes/parse.go
> -	s += "." + r.zone
This function will escape to stack.  Consider using strings.Join() instead of "+"

2017-08-18 20:34 UTC, miekg commented on middleware/kubernetes/parse.go
> -	s += "." + r.zone
sorry, what? You mean each s is a new string and therefor adds GC?
Sure I can change this.

2017-08-18 20:36 UTC, miekg commented on middleware/kubernetes/parse.go
> -	s += "." + r.zone
strings.Join requires a string slice to be constructed. If you worried about mem...

2017-08-18 21:08 UTC, chrisohaver commented on middleware/kubernetes/parse.go
> -	s += "." + r.zone
Oh ok, never mind then, i must be mistaken.

2017-08-18 21:09 UTC, chrisohaver approved these changes

2017-08-19 06:18 UTC, miekg commented
Travis 1.7 build failed with
~~~
$ docker run -d --net=host --name=etcd quay.io/coreos/etcd:v$ETCD_VERSION
Unable to find image 'quay.io/coreos/etcd:v2.3.1' locally
docker: Error response from daemon: Get https://quay.io/v2/coreos/etcd/manifests/v2.3.1: Get https://quay.io/v2/auth?scope=repository%3Acoreos%2Fetcd%3Apull&service=quay.io: net/http: TLS handshake timeout.
See 'docker run --help'.
~~~

2017-08-19 06:18 UTC, merged